// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// CreateBanner: Inserts a new banner
	// Parameters:
	//   $1: name
	//   $2: start_date
	//   $3: end_date
	//   $4: start_time
	//   $5: end_time
	//   $6: is_active
	// Returns: The newly created banner
	CreateBanner(ctx context.Context, arg CreateBannerParams) (*CreateBannerRow, error)
	// DeleteAllPermanentBanners: Permanently delete all trashed banners
	DeleteAllPermanentBanners(ctx context.Context) error
	// DeleteBannerPermanently: Permanently delete a single trashed banner
	// Parameters:
	//   $1: banner_id
	DeleteBannerPermanently(ctx context.Context, bannerID int32) error
	// GetBanner: Retrieves a single banner that is not soft-deleted
	// Parameters:
	//   $1: banner_id - ID of the banner
	// Business Logic:
	//   - Returns the banner where deleted_at IS NULL
	// Returns: A single banners record
	GetBanner(ctx context.Context, bannerID int32) (*GetBannerRow, error)
	// GetBanners: Retrieves all banners (active and trashed) with optional search and pagination
	// Parameters:
	//   $1: search - Keyword to filter banner name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Business Logic:
	//   - Returns all banners regardless of soft-delete status
	//   - Applies case-insensitive partial match on banner name
	//   - Supports pagination
	// Returns: List of all banners with total_count metadata
	GetBanners(ctx context.Context, arg GetBannersParams) ([]*GetBannersRow, error)
	// GetBannersActive: Retrieves active banners (not soft-deleted)
	// Parameters:
	//   $1: search - Keyword to filter banner name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Business Logic:
	//   - Returns banners where deleted_at IS NULL
	//   - Applies case-insensitive partial match on banner name
	//   - Supports pagination
	// Returns: List of active banners with total_count metadata
	GetBannersActive(ctx context.Context, arg GetBannersActiveParams) ([]*GetBannersActiveRow, error)
	// GetTrashedBanners: Retrieves soft-deleted (trashed) banners
	// Parameters:
	//   $1: search - Keyword to filter banner name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Business Logic:
	//   - Returns banners where deleted_at IS NOT NULL
	//   - Applies case-insensitive partial match on banner name
	//   - Supports pagination
	// Returns: List of trashed banners with total_count metadata
	GetBannersTrashed(ctx context.Context, arg GetBannersTrashedParams) ([]*GetBannersTrashedRow, error)
	// RestoreAllBanners: Restore all trashed banners
	RestoreAllBanners(ctx context.Context) error
	// RestoreBanner: Restores a soft-deleted banner
	// Parameters:
	//   $1: banner_id
	// Returns: The restored banner
	RestoreBanner(ctx context.Context, bannerID int32) (*Banner, error)
	// TrashBanner: Soft deletes a banner
	// Parameters:
	//   $1: banner_id
	// Returns: The trashed banner
	TrashBanner(ctx context.Context, bannerID int32) (*Banner, error)
	// UpdateBanner: Updates an existing banner
	// Parameters:
	//   $1: banner_id
	//   $2: name
	//   $3: start_date
	//   $4: end_date
	//   $5: start_time
	//   $6: end_time
	//   $7: is_active
	// Returns: The updated banner
	UpdateBanner(ctx context.Context, arg UpdateBannerParams) (*UpdateBannerRow, error)
}

var _ Querier = (*Queries)(nil)
