// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ReviewDetail struct {
	ReviewDetailID int32            `json:"review_detail_id"`
	ReviewID       int32            `json:"review_id"`
	Type           string           `json:"type"`
	Url            string           `json:"url"`
	Caption        *string          `json:"caption"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}
