// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// CreateReviewDetail: Inserts a new review detail
	// Parameters:
	//   $1: review_id - Foreign key to reviews table
	//   $2: type - Either 'photo' or 'video'
	//   $3: url - URL of the media
	//   $4: caption - Optional caption
	// Returns: The inserted review detail record
	CreateReviewDetail(ctx context.Context, arg CreateReviewDetailParams) (*CreateReviewDetailRow, error)
	// DeleteAllPermanentReviewDetails: Permanently deletes all trashed review details
	// Parameters: None
	// Business Logic:
	//   - Deletes all records where deleted_at IS NOT NULL
	// Returns: No return value (exec command)
	DeleteAllPermanentReviewDetails(ctx context.Context) error
	// DeletePermanentReviewDetail: Permanently deletes a soft-deleted review detail
	// Parameters:
	//   $1: review_detail_id - ID of the record to permanently delete
	// Business Logic:
	//   - Only deletes if deleted_at IS NOT NULL
	// Returns: No return value (exec command)
	DeletePermanentReviewDetail(ctx context.Context, reviewDetailID int32) error
	// GetReviewDetail: Retrieves a single review detail that is not soft-deleted
	// Parameters:
	//   $1: review_detail_id - ID of the review detail
	// Business Logic:
	//   - Returns the review detail where deleted_at IS NULL
	// Returns: A single review_details record
	GetReviewDetail(ctx context.Context, reviewDetailID int32) (*GetReviewDetailRow, error)
	// GetReviewDetailTrashed: Retrieves a single review detail that is not soft-deleted
	// Parameters:
	//   $1: review_detail_id - ID of the review detail
	// Business Logic:
	//   - Returns the review detail where deleted_at IS NULL
	// Returns: A single review_details record
	GetReviewDetailTrashed(ctx context.Context, reviewDetailID int32) (*ReviewDetail, error)
	// GetReviewDetails: Retrieves all review details (active and trashed)
	// Parameters:
	//   $1: search - Keyword to filter caption (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Business Logic:
	//   - Returns both active and trashed records
	//   - Applies case-insensitive partial search on caption
	//   - Supports pagination
	// Returns: List of review details with total_count metadata
	GetReviewDetails(ctx context.Context, arg GetReviewDetailsParams) ([]*GetReviewDetailsRow, error)
	// GetReviewDetailsActive: Retrieves active (non-deleted) review details
	// Parameters:
	//   $1: search - Keyword to filter caption (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Business Logic:
	//   - Returns only records where deleted_at IS NULL
	//   - Applies case-insensitive partial search on caption
	//   - Supports pagination
	// Returns: List of active review details with total_count metadata
	GetReviewDetailsActive(ctx context.Context, arg GetReviewDetailsActiveParams) ([]*GetReviewDetailsActiveRow, error)
	// GetTrashedReviewDetails: Retrieves trashed (soft-deleted) review details
	// Parameters:
	//   $1: search - Keyword to filter caption (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Business Logic:
	//   - Returns only records where deleted_at IS NOT NULL
	//   - Applies case-insensitive partial search on caption
	//   - Supports pagination
	// Returns: List of trashed review details with total_count metadata
	GetReviewDetailsTrashed(ctx context.Context, arg GetReviewDetailsTrashedParams) ([]*GetReviewDetailsTrashedRow, error)
	// RestoreAllReviewDetails: Restores all soft-deleted review details
	// Parameters: None
	// Business Logic:
	//   - Sets deleted_at to NULL for all trashed records
	// Returns: No return value (exec command)
	RestoreAllReviewDetails(ctx context.Context) error
	// RestoreReviewDetail: Restores a soft-deleted review detail
	// Parameters:
	//   $1: review_detail_id - ID of the record to restore
	// Business Logic:
	//   - Only restores if deleted_at IS NOT NULL
	// Returns: The restored review detail
	RestoreReviewDetail(ctx context.Context, reviewDetailID int32) (*ReviewDetail, error)
	// TrashReviewDetail: Soft deletes a review detail
	// Parameters:
	//   $1: review_detail_id - ID of the record to soft delete
	// Business Logic:
	//   - Only applies soft-delete if record is not already trashed
	// Returns: The soft-deleted review detail
	TrashReviewDetail(ctx context.Context, reviewDetailID int32) (*ReviewDetail, error)
	// UpdateReviewDetail: Updates an existing review detail
	// Parameters:
	//   $1: type - New media type
	//   $2: url - New media URL
	//   $3: caption - Updated caption
	//   $4: review_detail_id - Target record to update
	// Returns: The updated review detail record
	UpdateReviewDetail(ctx context.Context, arg UpdateReviewDetailParams) (*UpdateReviewDetailRow, error)
}

var _ Querier = (*Queries)(nil)
