// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ShippingAddress struct {
	ShippingAddressID int32            `json:"shipping_address_id"`
	OrderID           int32            `json:"order_id"`
	Alamat            string           `json:"alamat"`
	Provinsi          string           `json:"provinsi"`
	Negara            string           `json:"negara"`
	Kota              string           `json:"kota"`
	Courier           string           `json:"courier"`
	ShippingMethod    string           `json:"shipping_method"`
	ShippingCost      float64          `json:"shipping_cost"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	DeletedAt         pgtype.Timestamp `json:"deleted_at"`
}
