// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	OutboxID      int64            `json:"outbox_id"`
	Topic         string           `json:"topic"`
	EventKey      string           `json:"event_key"`
	Payload       []byte           `json:"payload"`
	Status        string           `json:"status"`
	Attempts      int32            `json:"attempts"`
	NextAttemptAt time.Time        `json:"next_attempt_at"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type RefreshToken struct {
	RefreshTokenID int32            `json:"refresh_token_id"`
	UserID         int32            `json:"user_id"`
	Token          string           `json:"token"`
	Expiration     time.Time        `json:"expiration"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

type ResetToken struct {
	ID         int32     `json:"id"`
	UserID     int64     `json:"user_id"`
	Token      string    `json:"token"`
	ExpiryDate time.Time `json:"expiry_date"`
}
