// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Review struct {
	ReviewID  int32            `json:"review_id"`
	UserID    int32            `json:"user_id"`
	ProductID int32            `json:"product_id"`
	Name      string           `json:"name"`
	Comment   string           `json:"comment"`
	Rating    int32            `json:"rating"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}
