// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// CreateReview: Creates a new product review
	// Purpose: Allow users to submit product reviews
	// Parameters:
	//   $1: user_id - ID of the user submitting review
	//   $2: product_id - ID of the product being reviewed
	//   $3: name - Display name for the review
	//   $4: comment - Review text content
	//   $5: rating - Numeric rating (typically 1-5)
	// Returns:
	//   The complete created review record
	// Business Logic:
	//   - Creates a new active review
	//   - Requires user_id and product_id for reference
	//   - Returns full record for immediate display
	CreateReview(ctx context.Context, arg CreateReviewParams) (*CreateReviewRow, error)
	// DeleteAllPermanentReviews: Purges all trashed reviews
	// Purpose: Clean up review recycle bin
	// Parameters: None
	// Returns:
	//   Nothing (exec-only)
	// Business Logic:
	//   - Permanent deletion of all trashed reviews
	//   - Admin-level operation
	//   - Irreversible bulk deletion
	DeleteAllPermanentReviews(ctx context.Context) error
	// DeleteReviewPermanently: Removes a review from database
	// Purpose: Permanent deletion of trashed reviews
	// Parameters:
	//   $1: review_id - ID of review to delete
	// Returns:
	//   Nothing (exec-only)
	// Business Logic:
	//   - Physical deletion of record
	//   - Only works on already-trashed reviews
	//   - Irreversible operation
	DeleteReviewPermanently(ctx context.Context, reviewID int32) error
	// GetReviewByID: Retrieves a single active review by ID
	// Purpose: Display review details in UI
	// Parameters:
	//   $1: review_id - ID of the review to retrieve
	// Returns:
	//   Complete review record if found and active
	// Business Logic:
	//   - Only returns non-deleted (active) reviews
	//   - Used for displaying individual review details
	GetReviewByID(ctx context.Context, reviewID int32) (*GetReviewByIDRow, error)
	// Retrieves paginated reviews for all products belonging to a merchant
	//
	// Purpose: Display all reviews for merchant's products in dashboard
	//
	// Parameters:
	//   $1: product_ids - IDs of the merchant's products (resolved via product
	//       service gRPC; the review service owns no products table)
	//   $2: rating_filter - Optional rating value to filter by (NULL for all ratings)
	//   $3: limit - Maximum number of records to return
	//   $4: offset - Number of records to skip for pagination
	//
	// Returns:
	//   - Review fields with aggregated review details (images/videos) as JSON array
	//   - Includes total_count for pagination
	//
	// Business Logic:
	//   - Only shows active (non-deleted) reviews
	//   - Filters by merchant's products through product_ids parameter (cross-DB
	//     JOIN removed; product ownership is resolved by the review service via gRPC)
	//   - Optional rating filter (1-5 stars)
	//   - review_details is a placeholder: reviews_detail lives in the
	//     review_detail service DB (1 DB per service), so the cross-DB subquery
	//     was removed. Media is served by the review_detail service instead.
	//   - Returns newest reviews first
	GetReviewByMerchantId(ctx context.Context, arg GetReviewByMerchantIdParams) ([]*GetReviewByMerchantIdRow, error)
	// Retrieves paginated list of product reviews with details and optional rating filter
	//
	// Purpose: Display reviews for a specific product in storefront
	//
	// Parameters:
	//   $1: product_id - ID of the product to get reviews for
	//   $2: rating_filter - Optional rating value to filter by (NULL for all ratings)
	//   $3: limit - Maximum number of records to return
	//   $4: offset - Number of records to skip for pagination
	//
	// Returns:
	//   - Review fields with aggregated review details (images/videos) as JSON array
	//   - Includes total_count for pagination
	//
	// Business Logic:
	//   - Only shows active (non-deleted) reviews
	//   - Filters by specific product only
	//   - Optional rating filter (1-5 stars)
	//   - review_details is a placeholder: reviews_detail lives in the
	//     review_detail service DB (1 DB per service), so the cross-DB subquery
	//     was removed. Media is served by the review_detail service instead.
	//   - Returns newest reviews first
	GetReviewByProductId(ctx context.Context, arg GetReviewByProductIdParams) ([]*GetReviewByProductIdRow, error)
	// GetReviews: Retrieves paginated list of all reviews (both active and trashed) with search capability
	// Purpose: Display reviews in admin dashboard
	// Parameters:
	//   $1: search_term - Optional text to filter reviews by ID or name (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All review fields plus total_count of matching records
	// Business Logic:
	//   - Includes both active and trashed reviews
	//   - Supports partial text matching on review_id (cast as text) and name fields (case-insensitive)
	//   - Returns newest reviews first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetReviews(ctx context.Context, arg GetReviewsParams) ([]*GetReviewsRow, error)
	// GetReviewsActive: Retrieves paginated list of active reviews with search capability
	// Purpose: Display active reviews in storefront/admin UI
	// Parameters:
	//   $1: search_term - Optional text to filter reviews by ID or name (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All review fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted reviews (deleted_at IS NULL)
	//   - Supports partial text matching on review_id (cast as text) and name fields (case-insensitive)
	//   - Returns newest reviews first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetReviewsActive(ctx context.Context, arg GetReviewsActiveParams) ([]*GetReviewsActiveRow, error)
	// GetReviewsTrashed: Retrieves paginated list of trashed reviews with search capability
	// Purpose: Display deleted reviews in admin recycle bin
	// Parameters:
	//   $1: search_term - Optional text to filter reviews by ID or name (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All review fields plus total_count of matching records
	// Business Logic:
	//   - Only includes soft-deleted reviews (deleted_at IS NOT NULL)
	//   - Supports partial text matching on review_id (cast as text) and name fields (case-insensitive)
	//   - Returns newest reviews first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetReviewsTrashed(ctx context.Context, arg GetReviewsTrashedParams) ([]*GetReviewsTrashedRow, error)
	// RestoreAllReviews: Recovers all soft-deleted reviews
	// Purpose: Bulk restore from trash/recycle bin
	// Parameters: None
	// Returns:
	//   Nothing (exec-only)
	// Business Logic:
	//   - Clears deleted_at for all trashed reviews
	//   - Admin-level operation
	//   - Returns all reviews to active status
	RestoreAllReviews(ctx context.Context) error
	// RestoreReview: Recovers a soft-deleted review
	// Purpose: Reactivate previously trashed reviews
	// Parameters:
	//   $1: review_id - ID of review to restore
	// Returns:
	//   The restored review record
	// Business Logic:
	//   - Clears deleted_at timestamp
	//   - Only works on trashed reviews
	//   - Returns review to active status
	RestoreReview(ctx context.Context, reviewID int32) (*Review, error)
	// TrashReview: Soft-deletes a review
	// Purpose: Remove review from public view while preserving data
	// Parameters:
	//   $1: review_id - ID of review to trash
	// Returns:
	//   The trashed review record
	// Business Logic:
	//   - Sets deleted_at timestamp
	//   - Only works on active reviews
	//   - Allows recovery via RestoreReview
	TrashReview(ctx context.Context, reviewID int32) (*Review, error)
	// UpdateReview: Modifies an existing review
	// Purpose: Allow users to edit their reviews
	// Parameters:
	//   $1: review_id - ID of review to update
	//   $2: name - Updated display name
	//   $3: comment - Updated review text
	//   $4: rating - Updated numeric rating
	// Returns:
	//   The updated review record
	// Business Logic:
	//   - Only updates mutable review fields
	//   - Requires review to be active (not deleted)
	//   - Automatically updates timestamp
	UpdateReview(ctx context.Context, arg UpdateReviewParams) (*UpdateReviewRow, error)
}

var _ Querier = (*Queries)(nil)
