// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	OrderID    int32            `json:"order_id"`
	UserID     int32            `json:"user_id"`
	MerchantID int32            `json:"merchant_id"`
	TotalPrice int32            `json:"total_price"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type OrderStockReservation struct {
	ReservationID int32            `json:"reservation_id"`
	OrderID       int32            `json:"order_id"`
	ProductID     int32            `json:"product_id"`
	Quantity      int32            `json:"quantity"`
	Status        string           `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type OutboxEvent struct {
	OutboxID      int64            `json:"outbox_id"`
	Topic         string           `json:"topic"`
	EventKey      string           `json:"event_key"`
	Payload       []byte           `json:"payload"`
	Status        string           `json:"status"`
	Attempts      int32            `json:"attempts"`
	NextAttemptAt time.Time        `json:"next_attempt_at"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type ProductStockAdjustment struct {
	OperationID string           `json:"operation_id"`
	ProductID   int32            `json:"product_id"`
	Delta       int32            `json:"delta"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
