// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ClaimPendingOutboxEvents: Atomically claims up to $1 pending events whose retry
	// window has elapsed. The claim extends next_attempt_at to $2 (the lease expiry)
	// so concurrent relay instances can never publish the same event twice; a crashed
	// worker's claim simply expires when the lease passes and the event is retried.
	ClaimPendingOutboxEvents(ctx context.Context, arg ClaimPendingOutboxEventsParams) ([]*OutboxEvent, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (*CreateOrderRow, error)
	// CreateOutboxEvent: Inserts a pending outbox event for durable Kafka publish.
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (*OutboxEvent, error)
	// DeleteAllOrderStockReservations: Removes reservations for permanently deleted orders.
	DeleteAllOrderStockReservations(ctx context.Context) error
	// DeleteAllPermanentOrders: Purges all cancelled orders
	// Purpose: Clean up all soft-deleted order records
	// Business Logic:
	//   - Irreversible bulk deletion operation
	//   - Only affects already cancelled orders
	//   - Typically used during database maintenance
	//   - Should be restricted to admin users
	DeleteAllPermanentOrders(ctx context.Context) error
	// DeleteOldOutboxEvents: Purges delivered/dead events older than the cutoff.
	DeleteOldOutboxEvents(ctx context.Context, updatedAt pgtype.Timestamp) (int64, error)
	// DeleteOldProductStockAdjustments: Purges idempotency ledger rows older than a cutoff.
	// Retention keeps the product_stock_adjustments table bounded without touching fresh rows
	// that may still be referenced by in-flight retries.
	DeleteOldProductStockAdjustments(ctx context.Context, createdAt pgtype.Timestamp) (int64, error)
	// DeleteOldReleasedReservations: Removes released reservations older than a cutoff for
	// trashed orders. Retention keeps the idempotency ledger bounded while preserving active
	// reservations; only trashed orders may have their released rows cleaned up.
	DeleteOldReleasedReservations(ctx context.Context, updatedAt pgtype.Timestamp) (int64, error)
	// DeleteOrderPermanently: Hard-deletes an order
	// Purpose: Completely remove order from database
	// Parameters:
	//   $1: order_id - UUID of order to delete
	// Business Logic:
	//   - Permanent deletion of already cancelled orders
	//   - No return value (exec-only operation)
	//   - Irreversible action - use with caution
	//   - Should trigger deletion of related order_items
	DeleteOrderPermanently(ctx context.Context, orderID int32) error
	// DeleteOrderPermanentlyWithChildren: Atomically purges a trashed order and all
	// of its child rows (stock reservations, order items, transactions, shipping
	// addresses) in a single statement so a mid-way failure cannot orphan children.
	// The trashed guard lives in a leading CTE that gates EVERY child delete, so a
	// call on a non-trashed order deletes nothing and returns no row (the caller
	// surfaces ErrOrderNotFound) instead of wiping children of an active order.
	// Purges a trashed order and its local child rows (stock reservations) in a
	// single statement. Order items, transactions, and shipping addresses live in
	// their own per-service databases (cross-DB FK split), so those children are
	// removed by the order service via gRPC calls to the owning services instead.
	// The trashed guard lives in a leading CTE that gates every child delete, so a
	// call on a non-trashed order deletes nothing and returns no row (the caller
	// surfaces ErrOrderNotFound) instead of wiping children of an active order.
	DeleteOrderPermanentlyWithChildren(ctx context.Context, orderID int32) (int32, error)
	// DeleteOrderStockReservation: Removes one reservation row for an order/product.
	DeleteOrderStockReservation(ctx context.Context, arg DeleteOrderStockReservationParams) error
	// DeleteOrderStockReservations: Removes reservation rows for a permanently deleted order.
	DeleteOrderStockReservations(ctx context.Context, orderID int32) error
	// GetOrderByID: Retrieves an active order by ID
	// Purpose: Fetch order details for display/processing
	// Parameters:
	//   $1: order_id - UUID of the order to retrieve
	// Returns: Full order record if found and active
	// Business Logic:
	//   - Excludes soft-deleted orders
	//   - Used for order viewing, receipts, and processing
	//   - Typically joined with order_items in application
	GetOrderByID(ctx context.Context, orderID int32) (*GetOrderByIDRow, error)
	// GetOrderStockReservationsByOrder: Retrieves reservations for an order.
	GetOrderStockReservationsByOrder(ctx context.Context, orderID int32) ([]*OrderStockReservation, error)
	GetOrders(ctx context.Context, arg GetOrdersParams) ([]*GetOrdersRow, error)
	// GetOrdersActive: Retrieves paginated list of active orders (identical to GetOrders)
	// Purpose: Maintains consistent API pattern with other active/trashed endpoints
	// Parameters:
	//   $1: search_term - Optional filter text for order ID or price
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns:
	//   Active order records with total_count
	// Business Logic:
	//   - Same functionality as GetOrders
	//   - Exists for consistency in API design patterns
	// Note: Could be consolidated with GetOrders if duplicate functionality is undesired
	GetOrdersActive(ctx context.Context, arg GetOrdersActiveParams) ([]*GetOrdersActiveRow, error)
	// GetOrdersByMerchant: Retrieves merchant-specific orders with pagination
	// Purpose: List orders filtered by merchant ID
	// Parameters:
	//   $1: search_term - Optional text to filter orders
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	//   $4: merchant_id - Optional merchant UUID to filter by (NULL for all merchants)
	// Returns:
	//   Order records with total_count
	// Business Logic:
	//   - Combines merchant filtering with search functionality
	//   - Maintains same sorting and pagination as other order queries
	//   - Useful for merchant-specific order dashboards
	//   - NULL merchant_id parameter returns all merchants' orders
	GetOrdersByMerchant(ctx context.Context, arg GetOrdersByMerchantParams) ([]*GetOrdersByMerchantRow, error)
	// GetOrdersTrashed: Retrieves paginated list of soft-deleted orders
	// Purpose: View and manage deleted orders for potential restoration
	// Parameters:
	//   $1: search_term - Optional text to filter trashed orders
	//   $2: limit - Maximum records per page
	//   $3: offset - Records to skip
	// Returns:
	//   Trashed order records with total_count
	// Business Logic:
	//   - Only returns soft-deleted records (deleted_at IS NOT NULL)
	//   - Maintains same search functionality as active order queries
	//   - Preserves chronological sorting (newest first)
	//   - Used in order recovery/audit interfaces
	//   - Includes total_count for pagination in trash management UI
	GetOrdersTrashed(ctx context.Context, arg GetOrdersTrashedParams) ([]*GetOrdersTrashedRow, error)
	// GetPendingOutboxEvents: Returns pending events whose retry window has elapsed.
	GetPendingOutboxEvents(ctx context.Context, limit int32) ([]*OutboxEvent, error)
	// GetReleasedReservationsForActiveOrders: Finds reservations marked released that belong to
	// still-active orders. This is a drift pattern that durable reconciliation must repair by
	// re-reserving stock (an order should only release stock when it is trashed or completed).
	GetReleasedReservationsForActiveOrders(ctx context.Context) ([]*OrderStockReservation, error)
	// GetReleasedStockReservationsForTrashedOrders: Finds released reservations belonging to trashed orders.
	GetReleasedStockReservationsForTrashedOrders(ctx context.Context) ([]*OrderStockReservation, error)
	// GetReservedStockReservationsForTrashedOrders: Finds active reservations belonging to trashed orders.
	GetReservedStockReservationsForTrashedOrders(ctx context.Context) ([]*OrderStockReservation, error)
	// GetTrashedOrder: Retrieves one soft-deleted order for guarded permanent deletion.
	GetTrashedOrder(ctx context.Context, orderID int32) (*Order, error)
	// GetTrashedOrders: Retrieves all soft-deleted orders for per-order restoration.
	GetTrashedOrders(ctx context.Context) ([]*Order, error)
	// MarkOrderStockReservationReleased: Marks one active reservation as released.
	MarkOrderStockReservationReleased(ctx context.Context, arg MarkOrderStockReservationReleasedParams) (*OrderStockReservation, error)
	// MarkOrderStockReservationReserved: Marks one released reservation as reserved.
	MarkOrderStockReservationReserved(ctx context.Context, arg MarkOrderStockReservationReservedParams) (*OrderStockReservation, error)
	// MarkOutboxEventDead: Marks a pending event as dead after exhausting retries.
	MarkOutboxEventDead(ctx context.Context, outboxID int64) (*OutboxEvent, error)
	// MarkOutboxEventDelivered: Marks a pending event as delivered.
	MarkOutboxEventDelivered(ctx context.Context, outboxID int64) (*OutboxEvent, error)
	// MarkOutboxEventFailed: Increments the attempt counter and schedules the next
	// attempt at the provided timestamp (backoff computed by the caller).
	MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) (*OutboxEvent, error)
	// RestoreAllOrders: Mass restoration of cancelled orders
	// Purpose: Recover all trashed orders at once
	// Business Logic:
	//   - Reactivates all soft-deleted orders
	//   - No parameters needed (bulk operation)
	//   - Typically used during system recovery
	RestoreAllOrders(ctx context.Context) error
	// RestoreOrder: Recovers a soft-deleted order
	// Purpose: Reactivate a cancelled order
	// Parameters:
	//   $1: order_id - UUID of order to restore
	// Returns: The restored order record
	// Business Logic:
	//   - Nullifies deleted_at field
	//   - Only works on previously cancelled orders
	//   - Maintains all original order data
	RestoreOrder(ctx context.Context, orderID int32) (*Order, error)
	// TrashedOrder: Soft-deletes an order
	// Purpose: Cancel/void an order without permanent deletion
	// Parameters:
	//   $1: order_id - UUID of order to cancel
	// Returns: The soft-deleted order record
	// Business Logic:
	//   - Sets deleted_at to current timestamp
	//   - Preserves order data for reporting
	//   - Only processes active orders
	//   - Can be restored via RestoreOrder
	TrashedOrder(ctx context.Context, orderID int32) (*Order, error)
	// UpdateOrder: Modifies order information
	// Purpose: Update order details (primarily total price)
	// Parameters:
	//   $1: order_id - UUID of order to update
	//   $2: total_price - New total amount
	// Returns: Updated order record
	// Business Logic:
	//   - Auto-updates updated_at timestamp
	//   - Only modifies active (non-deleted) orders
	//   - Used when order items change
	//   - Should trigger recalculation of total_price
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (*UpdateOrderRow, error)
	// UpdateOrderStockReservationQuantity: Sets the active reservation quantity.
	UpdateOrderStockReservationQuantity(ctx context.Context, arg UpdateOrderStockReservationQuantityParams) (*OrderStockReservation, error)
	// UpsertOrderStockReservation: Adds quantity to an order/product reservation.
	UpsertOrderStockReservation(ctx context.Context, arg UpsertOrderStockReservationParams) (*OrderStockReservation, error)
}

var _ Querier = (*Queries)(nil)
