// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MerchantCertificationsAndAward struct {
	MerchantCertificationID int32            `json:"merchant_certification_id"`
	MerchantID              int32            `json:"merchant_id"`
	Title                   string           `json:"title"`
	Description             *string          `json:"description"`
	IssuedBy                *string          `json:"issued_by"`
	IssueDate               pgtype.Date      `json:"issue_date"`
	ExpiryDate              pgtype.Date      `json:"expiry_date"`
	CertificateUrl          *string          `json:"certificate_url"`
	CreatedAt               pgtype.Timestamp `json:"created_at"`
	UpdatedAt               pgtype.Timestamp `json:"updated_at"`
	DeletedAt               pgtype.Timestamp `json:"deleted_at"`
}
