// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// CreateMerchantCertificationOrAward: Inserts a new certification or award
	// Purpose: Register a new certification or award for a merchant
	// Parameters:
	//   $1: merchant_id
	//   $2: title
	//   $3: description
	//   $4: issued_by
	//   $5: issue_date
	//   $6: expiry_date
	//   $7: certificate_url
	// Returns: The newly created certification record
	// Business Logic:
	//   - Sets created_at automatically
	//   - Requires merchant_id and title
	CreateMerchantCertificationOrAward(ctx context.Context, arg CreateMerchantCertificationOrAwardParams) (*CreateMerchantCertificationOrAwardRow, error)
	// DeleteAllPermanentMerchantCertificationsAndAwards: Hard-deletes all trashed certifications
	// Purpose: Bulk clean-up operation
	// Business Logic:
	//   - Irreversible delete for all soft-deleted records
	//   - Should be restricted to admin-level actions
	DeleteAllPermanentMerchantCertificationsAndAwards(ctx context.Context) error
	// DeleteMerchantCertificationOrAwardPermanently: Hard-deletes a certification record
	// Purpose: Permanently remove a soft-deleted record
	// Parameters:
	//   $1: merchant_certification_id
	// Business Logic:
	//   - Only affects already soft-deleted records
	//   - Irreversible action
	DeleteMerchantCertificationOrAwardPermanently(ctx context.Context, merchantCertificationID int32) error
	// GetMerchantCertificationOrAward: Retrieves a single merchant award or certification that is not soft-deleted
	// Parameters:
	//   $1: merchant_certification_id - ID of the award/certification
	// Business Logic:
	//   - Returns the merchant award or certification where deleted_at IS NULL
	// Returns: A single merchant_certifications_and_awards record
	GetMerchantCertificationOrAward(ctx context.Context, merchantCertificationID int32) (*GetMerchantCertificationOrAwardRow, error)
	// GetMerchantCertificationsAndAwards: Retrieves all certification records with pagination and optional search
	// Parameters:
	//   $1: search - Keyword to filter merchant_name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Business Logic:
	//   - Fetches certifications regardless of merchant status (active or deleted)
	//   - Supports case-insensitive partial search by merchant name
	//   - Applies pagination using limit and offset
	// Returns: Certification records matching the search, with total_count
	// Note: merchants lives in the merchant service DB (per-service split), so the
	//   cross-DB JOIN is removed and merchant_name is a placeholder; the search
	//   param is kept for signature stability and matches everything.
	GetMerchantCertificationsAndAwards(ctx context.Context, arg GetMerchantCertificationsAndAwardsParams) ([]*GetMerchantCertificationsAndAwardsRow, error)
	// GetMerchantCertificationsAndAwardsActive: Retrieves certifications for active merchants with pagination and optional search
	// Parameters:
	//   $1: search - Keyword to filter merchant_name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Business Logic:
	//   - Fetches certifications only for active merchants (deleted_at IS NULL)
	//   - Supports case-insensitive partial search by merchant name
	//   - Applies pagination using limit and offset
	// Returns: Active merchant certification records matching the search, with total_count
	// Note: merchants lives in the merchant service DB (per-service split), so the
	//   cross-DB JOIN is removed and merchant_name is a placeholder; the search
	//   param is kept for signature stability and matches everything.
	GetMerchantCertificationsAndAwardsActive(ctx context.Context, arg GetMerchantCertificationsAndAwardsActiveParams) ([]*GetMerchantCertificationsAndAwardsActiveRow, error)
	// GetMerchantCertificationsAndAwardsTrashed: Retrieves certifications for deleted merchants with pagination and optional search
	// Parameters:
	//   $1: search - Keyword to filter merchant_name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Business Logic:
	//   - Fetches certifications only for deleted merchants (deleted_at IS NOT NULL)
	//   - Supports case-insensitive partial search by merchant name
	//   - Applies pagination using limit and offset
	// Returns: Trashed merchant certification records matching the search, with total_count
	// Note: merchants lives in the merchant service DB (per-service split), so the
	//   cross-DB JOIN is removed and merchant_name is a placeholder; the search
	//   param is kept for signature stability and matches everything.
	GetMerchantCertificationsAndAwardsTrashed(ctx context.Context, arg GetMerchantCertificationsAndAwardsTrashedParams) ([]*GetMerchantCertificationsAndAwardsTrashedRow, error)
	// RestoreAllMerchantCertificationsAndAwards: Restores all soft-deleted certifications
	// Purpose: Bulk restore operation
	// Business Logic:
	//   - Clears deleted_at field from all trashed records
	//   - Useful for recovery or admin batch restore
	RestoreAllMerchantCertificationsAndAwards(ctx context.Context) error
	// RestoreMerchantCertificationOrAward: Restores a soft-deleted certification
	// Purpose: Reactivate a previously deleted record
	// Parameters:
	//   $1: merchant_certification_id
	// Returns: The restored record
	// Business Logic:
	//   - Clears deleted_at
	//   - Only works on previously soft-deleted entries
	RestoreMerchantCertificationOrAward(ctx context.Context, merchantCertificationID int32) (*MerchantCertificationsAndAward, error)
	// TrashMerchantCertificationOrAward: Soft-deletes a certification or award
	// Purpose: Deactivate a record without permanent deletion
	// Parameters:
	//   $1: merchant_certification_id
	// Returns: The soft-deleted certification record
	// Business Logic:
	//   - Sets deleted_at timestamp
	//   - Only affects active records
	TrashMerchantCertificationOrAward(ctx context.Context, merchantCertificationID int32) (*MerchantCertificationsAndAward, error)
	// UpdateMerchantCertificationOrAward: Updates an existing certification or award
	// Purpose: Modify certification or award details
	// Parameters:
	//   $1: merchant_certification_id
	//   $2: title
	//   $3: description
	//   $4: issued_by
	//   $5: issue_date
	//   $6: expiry_date
	//   $7: certificate_url
	// Returns: The updated certification record
	// Business Logic:
	//   - Only affects active (non-deleted) records
	//   - Automatically updates the updated_at timestamp
	UpdateMerchantCertificationOrAward(ctx context.Context, arg UpdateMerchantCertificationOrAwardParams) (*UpdateMerchantCertificationOrAwardRow, error)
}

var _ Querier = (*Queries)(nil)
