// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MerchantPolicy struct {
	MerchantPolicyID int32            `json:"merchant_policy_id"`
	MerchantID       int32            `json:"merchant_id"`
	PolicyType       string           `json:"policy_type"`
	Title            string           `json:"title"`
	Description      string           `json:"description"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
}
