// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// CreateMerchantPolicy: Inserts a new merchant policy
	// Purpose: Register a new policy for a merchant
	// Parameters:
	//   $1: merchant_id
	//   $2: policy_type
	//   $3: title
	//   $4: description
	// Returns: The newly created policy record
	// Business Logic:
	//   - Sets created_at, updated_at automatically
	CreateMerchantPolicy(ctx context.Context, arg CreateMerchantPolicyParams) (*CreateMerchantPolicyRow, error)
	// DeleteMerchantPolicyPermanently: Hard-deletes a policy record
	// Purpose: Permanently remove a soft-deleted policy
	// Parameters:
	//   $1: merchant_policy_id
	// Business Logic:
	//   - Irreversible delete
	//   - Only affects already soft-deleted records
	DeleteAllMerchantPolicyPermanently(ctx context.Context) error
	// DeleteMerchantPolicyPermanently: Hard-deletes a policy record
	// Purpose: Permanently remove a soft-deleted policy
	// Parameters:
	//   $1: merchant_policy_id
	// Business Logic:
	//   - Irreversible delete
	//   - Only affects already soft-deleted records
	DeleteMerchantPolicyPermanently(ctx context.Context, merchantPolicyID int32) error
	// GetMerchantPolicies: Retrieves all merchant policies regardless of merchant status
	// Parameters:
	//   $1: search - Keyword to filter merchant_name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns: Merchant policy records with merchant name and total_count
	// Note: merchants lives in the merchant service DB (per-service split), so the
	//   cross-DB JOIN is removed and merchant_name is a placeholder; the search
	//   param is kept for signature stability and matches everything.
	GetMerchantPolicies(ctx context.Context, arg GetMerchantPoliciesParams) ([]*GetMerchantPoliciesRow, error)
	// GetMerchantPoliciesActive: Retrieves merchant policies for active merchants
	// Parameters:
	//   $1: search - Keyword to filter merchant_name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns: Active merchant policy records with merchant name and total_count
	// Note: merchants lives in the merchant service DB (per-service split), so the
	//   cross-DB JOIN is removed and merchant_name is a placeholder; the search
	//   param is kept for signature stability and matches everything.
	GetMerchantPoliciesActive(ctx context.Context, arg GetMerchantPoliciesActiveParams) ([]*GetMerchantPoliciesActiveRow, error)
	// GetMerchantPoliciesTrashed: Retrieves merchant policies for deleted merchants
	// Parameters:
	//   $1: search - Keyword to filter merchant_name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns: Trashed merchant policy records with merchant name and total_count
	// Note: merchants lives in the merchant service DB (per-service split), so the
	//   cross-DB JOIN is removed and merchant_name is a placeholder; the search
	//   param is kept for signature stability and matches everything.
	GetMerchantPoliciesTrashed(ctx context.Context, arg GetMerchantPoliciesTrashedParams) ([]*GetMerchantPoliciesTrashedRow, error)
	// GetMerchantPolicy: Retrieves a single merchant policy that is not soft-deleted
	// Parameters:
	//   $1: merchant_policy_id - ID of the merchant policy
	// Business Logic:
	//   - Returns the merchant policy where deleted_at IS NULL
	// Returns: A single merchant_policies record
	GetMerchantPolicy(ctx context.Context, merchantPolicyID int32) (*GetMerchantPolicyRow, error)
	// RestoreAllMerchantPolicies: Restores all soft-deleted merchant policies
	// Purpose: Bulk recovery operation
	// Business Logic:
	//   - Clears deleted_at on all trashed records
	RestoreAllMerchantPolicies(ctx context.Context) error
	// RestoreMerchantPolicy: Restores a soft-deleted policy
	// Purpose: Reactivate a previously deleted policy
	// Parameters:
	//   $1: merchant_policy_id
	// Returns: The restored policy record
	// Business Logic:
	//   - Clears deleted_at
	//   - Only works on previously soft-deleted entries
	RestoreMerchantPolicy(ctx context.Context, merchantPolicyID int32) (*MerchantPolicy, error)
	// TrashMerchantPolicy: Soft-deletes a merchant policy
	// Purpose: Temporarily deactivate a policy without permanent deletion
	// Parameters:
	//   $1: merchant_policy_id
	// Returns: The soft-deleted policy record
	// Business Logic:
	//   - Sets deleted_at timestamp
	//   - Only affects active records
	TrashMerchantPolicy(ctx context.Context, merchantPolicyID int32) (*MerchantPolicy, error)
	// UpdateMerchantPolicy: Updates an existing merchant policy
	// Purpose: Modify policy details
	// Parameters:
	//   $1: merchant_policy_id
	//   $2: policy_type
	//   $3: title
	//   $4: description
	// Returns: The updated policy record
	// Business Logic:
	//   - Only affects active (non-deleted) records
	//   - Automatically updates updated_at timestamps
	UpdateMerchantPolicy(ctx context.Context, arg UpdateMerchantPolicyParams) (*UpdateMerchantPolicyRow, error)
}

var _ Querier = (*Queries)(nil)
