// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	OutboxID      int64            `json:"outbox_id"`
	Topic         string           `json:"topic"`
	EventKey      string           `json:"event_key"`
	Payload       []byte           `json:"payload"`
	Status        string           `json:"status"`
	Attempts      int32            `json:"attempts"`
	NextAttemptAt time.Time        `json:"next_attempt_at"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Transaction struct {
	TransactionID int32            `json:"transaction_id"`
	OrderID       int32            `json:"order_id"`
	MerchantID    int32            `json:"merchant_id"`
	PaymentMethod string           `json:"payment_method"`
	Amount        int32            `json:"amount"`
	PaymentStatus string           `json:"payment_status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
}
