// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ClaimPendingOutboxEvents: Atomically claims up to $1 pending events whose retry
	// window has elapsed. The claim extends next_attempt_at to $2 (the lease expiry)
	// so concurrent relay instances can never publish the same event twice; a crashed
	// worker's claim simply expires when the lease passes and the event is retried.
	ClaimPendingOutboxEvents(ctx context.Context, arg ClaimPendingOutboxEventsParams) ([]*OutboxEvent, error)
	// CreateOutboxEvent: Inserts a pending outbox event for durable Kafka publish.
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (*OutboxEvent, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (*CreateTransactionRow, error)
	// DeleteAllPermanentTransactions: Purges all cancelled transactions
	// Purpose: Clean up all soft-deleted transaction records
	// Business Logic:
	//   - Irreversible bulk deletion operation
	//   - Only affects already cancelled transactions
	//   - Typically used during database maintenance
	//   - Should be restricted to admin users
	// Purges all soft-deleted transactions. The orders cross-DB subquery was
	// removed: orders live in the order service DB (1 DB per service), so cleanup
	// of transactions whose parent order is trashed happens per-order via
	// DeleteTransactionByOrderPermanent instead.
	DeleteAllPermanentTransactions(ctx context.Context) error
	// DeleteOldOutboxEvents: Purges delivered/dead events older than the cutoff.
	DeleteOldOutboxEvents(ctx context.Context, updatedAt pgtype.Timestamp) (int64, error)
	// DeleteTransactionByOrderPermanent: Permanently deletes all transactions for a specific order
	// Purpose: Cascading cleanup during order permanent deletion
	// Parameters:
	//   $1: order_id
	DeleteTransactionByOrderPermanent(ctx context.Context, orderID int32) error
	// DeleteTransactionPermanently: Hard-deletes a transaction
	// Purpose: Completely remove transaction from database
	// Parameters:
	//   $1: transaction_id - ID of transaction to delete
	// Business Logic:
	//   - Permanent deletion of already cancelled transactions
	//   - No return value (exec-only operation)
	//   - Irreversible action - use with caution
	//   - Should be restricted to admin users
	DeleteTransactionPermanently(ctx context.Context, transactionID int32) error
	// GetPendingOutboxEvents: Returns pending events whose retry window has elapsed.
	GetPendingOutboxEvents(ctx context.Context, limit int32) ([]*OutboxEvent, error)
	// GetTransactionByID: Retrieves transaction by transaction ID
	// Purpose: Fetch specific transaction details
	// Parameters:
	//   $1: transaction_id - The unique transaction ID
	// Returns: Full transaction record if active
	// Business Logic:
	//   - Excludes deleted transactions
	//   - Used for transaction details/receipts
	//   - Primary lookup for transaction management
	GetTransactionByID(ctx context.Context, transactionID int32) (*GetTransactionByIDRow, error)
	// GetTransactionByMerchant: Retrieves merchant-specific transactions with pagination
	// Purpose: List transactions filtered by merchant ID
	// Parameters:
	//   $1: search_term - Optional text to filter transactions
	//   $2: merchant_id - Optional merchant ID to filter by (NULL for all merchants)
	//   $3: limit - Pagination limit
	//   $4: offset - Pagination offset
	// Returns:
	//   Transaction records with total_count
	// Business Logic:
	//   - Combines merchant filtering with search functionality
	//   - Maintains same sorting and pagination as other transaction queries
	//   - Useful for merchant-specific transaction reporting
	//   - NULL merchant_id parameter returns all merchants' transactions
	GetTransactionByMerchant(ctx context.Context, arg GetTransactionByMerchantParams) ([]*GetTransactionByMerchantRow, error)
	// GetTransactionByOrderID: Retrieves transaction by order reference
	// Purpose: Lookup transaction associated with specific order
	// Parameters:
	//   $1: order_id - The order ID to search by
	// Returns: Transaction record if found and active
	// Business Logic:
	//   - Only returns non-deleted transactions
	//   - Used for order payment verification
	//   - Helps prevent duplicate payments
	GetTransactionByOrderID(ctx context.Context, orderID int32) (*GetTransactionByOrderIDRow, error)
	GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]*GetTransactionsRow, error)
	// GetTransactionsActive: Retrieves paginated list of active transactions (identical to GetTransactions)
	// Purpose: Maintains consistent API pattern with other active/trashed endpoints
	// Parameters:
	//   $1: search_term - Optional filter text for payment method/status
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns:
	//   Active transaction records with total_count
	// Business Logic:
	//   - Same functionality as GetTransactions
	//   - Exists for consistency in API design patterns
	// Note: Could be consolidated with GetTransactions if duplicate functionality is undesired
	GetTransactionsActive(ctx context.Context, arg GetTransactionsActiveParams) ([]*GetTransactionsActiveRow, error)
	// GetTransactionsTrashed: Retrieves paginated list of soft-deleted transactions
	// Purpose: View and manage deleted transactions for audit/recovery
	// Parameters:
	//   $1: search_term - Optional text to filter trashed transactions
	//   $2: limit - Maximum records per page
	//   $3: offset - Records to skip
	// Returns:
	//   Trashed transaction records with total_count
	// Business Logic:
	//   - Only returns soft-deleted records (deleted_at IS NOT NULL)
	//   - Maintains same search functionality as active transaction queries
	//   - Preserves chronological sorting (newest first)
	//   - Used in transaction recovery/audit interfaces
	//   - Includes total_count for pagination in trash management UI
	GetTransactionsTrashed(ctx context.Context, arg GetTransactionsTrashedParams) ([]*GetTransactionsTrashedRow, error)
	// MarkOutboxEventDead: Marks a pending event as dead after exhausting retries.
	MarkOutboxEventDead(ctx context.Context, outboxID int64) (*OutboxEvent, error)
	// MarkOutboxEventDelivered: Marks a pending event as delivered.
	MarkOutboxEventDelivered(ctx context.Context, outboxID int64) (*OutboxEvent, error)
	// MarkOutboxEventFailed: Increments the attempt counter and schedules the next
	// attempt at the provided timestamp (backoff computed by the caller).
	MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) (*OutboxEvent, error)
	// RestoreAllTransactions: Mass restoration of cancelled transactions
	// Purpose: Recover all trashed transactions at once
	// Business Logic:
	//   - Reactivates all soft-deleted transactions
	//   - No parameters needed (bulk operation)
	//   - Typically used during system recovery
	RestoreAllTransactions(ctx context.Context) error
	// RestoreTransaction: Recovers a soft-deleted transaction
	// Purpose: Reactivate a cancelled transaction
	// Parameters:
	//   $1: transaction_id - ID of transaction to restore
	// Returns: The restored transaction record
	// Business Logic:
	//   - Nullifies deleted_at field
	//   - Only works on previously cancelled transactions
	//   - Maintains all original transaction data
	RestoreTransaction(ctx context.Context, transactionID int32) (*Transaction, error)
	// TrashTransaction: Soft-deletes a transaction
	// Purpose: Void/cancel a transaction without permanent deletion
	// Parameters:
	//   $1: transaction_id - ID of transaction to cancel
	// Returns: The soft-deleted transaction record
	// Business Logic:
	//   - Sets deleted_at to current timestamp
	//   - Preserves transaction for reporting
	//   - Only processes active transactions
	//   - Can be restored if needed
	TrashTransaction(ctx context.Context, transactionID int32) (*Transaction, error)
	// UpdateTransaction: Modifies transaction details
	// Purpose: Update transaction information
	// Parameters:
	//   $1: transaction_id - ID of transaction to update
	//   $2: merchant_id - Updated merchant reference
	//   $3: payment_method - Updated payment method
	//   $4: amount - Updated transaction amount
	//   $5: change_amount - Updated change amount
	//   $6: payment_status - Updated payment status
	//   $7: order_id - Updated order reference
	// Returns: Updated transaction record
	// Business Logic:
	//   - Auto-updates updated_at timestamp
	//   - Only modifies active transactions
	//   - Validates all payment fields
	//   - Used for payment corrections/updates
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (*UpdateTransactionRow, error)
}

var _ Querier = (*Queries)(nil)
