// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    order_id, merchant_id, payment_method, amount, payment_status
) VALUES ($1, $2, $3, $4, $5)
RETURNING transaction_id,
    order_id,
    merchant_id,
    payment_method,
    amount,
    payment_status,
    created_at,
    updated_at
`

type CreateTransactionParams struct {
	OrderID       int32  `json:"order_id"`
	MerchantID    int32  `json:"merchant_id"`
	PaymentMethod string `json:"payment_method"`
	Amount        int32  `json:"amount"`
	PaymentStatus string `json:"payment_status"`
}

type CreateTransactionRow struct {
	TransactionID int32            `json:"transaction_id"`
	OrderID       int32            `json:"order_id"`
	MerchantID    int32            `json:"merchant_id"`
	PaymentMethod string           `json:"payment_method"`
	Amount        int32            `json:"amount"`
	PaymentStatus string           `json:"payment_status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (*CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.OrderID,
		arg.MerchantID,
		arg.PaymentMethod,
		arg.Amount,
		arg.PaymentStatus,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MerchantID,
		&i.PaymentMethod,
		&i.Amount,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteAllPermanentTransactions = `-- name: DeleteAllPermanentTransactions :exec
DELETE FROM transactions
WHERE
    deleted_at IS NOT NULL
`

// DeleteAllPermanentTransactions: Purges all cancelled transactions
// Purpose: Clean up all soft-deleted transaction records
// Business Logic:
//   - Irreversible bulk deletion operation
//   - Only affects already cancelled transactions
//   - Typically used during database maintenance
//   - Should be restricted to admin users
//
// Purges all soft-deleted transactions. The orders cross-DB subquery was
// removed: orders live in the order service DB (1 DB per service), so cleanup
// of transactions whose parent order is trashed happens per-order via
// DeleteTransactionByOrderPermanent instead.
func (q *Queries) DeleteAllPermanentTransactions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllPermanentTransactions)
	return err
}

const deleteTransactionByOrderPermanent = `-- name: DeleteTransactionByOrderPermanent :exec
DELETE FROM transactions
WHERE
    order_id = $1
`

// DeleteTransactionByOrderPermanent: Permanently deletes all transactions for a specific order
// Purpose: Cascading cleanup during order permanent deletion
// Parameters:
//
//	$1: order_id
func (q *Queries) DeleteTransactionByOrderPermanent(ctx context.Context, orderID int32) error {
	_, err := q.db.Exec(ctx, deleteTransactionByOrderPermanent, orderID)
	return err
}

const deleteTransactionPermanently = `-- name: DeleteTransactionPermanently :exec
DELETE FROM transactions WHERE transaction_id = $1 AND deleted_at IS NOT NULL
`

// DeleteTransactionPermanently: Hard-deletes a transaction
// Purpose: Completely remove transaction from database
// Parameters:
//
//	$1: transaction_id - ID of transaction to delete
//
// Business Logic:
//   - Permanent deletion of already cancelled transactions
//   - No return value (exec-only operation)
//   - Irreversible action - use with caution
//   - Should be restricted to admin users
func (q *Queries) DeleteTransactionPermanently(ctx context.Context, transactionID int32) error {
	_, err := q.db.Exec(ctx, deleteTransactionPermanently, transactionID)
	return err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT transaction_id,
    order_id,
    merchant_id,
    payment_method,
    amount,
    payment_status,
    created_at,
    updated_at
FROM transactions
WHERE transaction_id = $1
  AND deleted_at IS NULL
`

type GetTransactionByIDRow struct {
	TransactionID int32            `json:"transaction_id"`
	OrderID       int32            `json:"order_id"`
	MerchantID    int32            `json:"merchant_id"`
	PaymentMethod string           `json:"payment_method"`
	Amount        int32            `json:"amount"`
	PaymentStatus string           `json:"payment_status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

// GetTransactionByID: Retrieves transaction by transaction ID
// Purpose: Fetch specific transaction details
// Parameters:
//
//	$1: transaction_id - The unique transaction ID
//
// Returns: Full transaction record if active
// Business Logic:
//   - Excludes deleted transactions
//   - Used for transaction details/receipts
//   - Primary lookup for transaction management
func (q *Queries) GetTransactionByID(ctx context.Context, transactionID int32) (*GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, transactionID)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MerchantID,
		&i.PaymentMethod,
		&i.Amount,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTransactionByMerchant = `-- name: GetTransactionByMerchant :many
SELECT
    transaction_id, order_id, merchant_id, payment_method, amount, payment_status, created_at, updated_at, deleted_at,
    COUNT(*) OVER() AS total_count
FROM transactions
WHERE deleted_at IS NULL
  AND ($1::TEXT IS NULL OR payment_method ILIKE '%' || $1 || '%' OR payment_status ILIKE '%' || $1 || '%')
  AND ($2::INT IS NULL OR merchant_id = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetTransactionByMerchantParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetTransactionByMerchantRow struct {
	TransactionID int32            `json:"transaction_id"`
	OrderID       int32            `json:"order_id"`
	MerchantID    int32            `json:"merchant_id"`
	PaymentMethod string           `json:"payment_method"`
	Amount        int32            `json:"amount"`
	PaymentStatus string           `json:"payment_status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	TotalCount    int64            `json:"total_count"`
}

// GetTransactionByMerchant: Retrieves merchant-specific transactions with pagination
// Purpose: List transactions filtered by merchant ID
// Parameters:
//
//	$1: search_term - Optional text to filter transactions
//	$2: merchant_id - Optional merchant ID to filter by (NULL for all merchants)
//	$3: limit - Pagination limit
//	$4: offset - Pagination offset
//
// Returns:
//
//	Transaction records with total_count
//
// Business Logic:
//   - Combines merchant filtering with search functionality
//   - Maintains same sorting and pagination as other transaction queries
//   - Useful for merchant-specific transaction reporting
//   - NULL merchant_id parameter returns all merchants' transactions
func (q *Queries) GetTransactionByMerchant(ctx context.Context, arg GetTransactionByMerchantParams) ([]*GetTransactionByMerchantRow, error) {
	rows, err := q.db.Query(ctx, getTransactionByMerchant,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetTransactionByMerchantRow
	for rows.Next() {
		var i GetTransactionByMerchantRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.OrderID,
			&i.MerchantID,
			&i.PaymentMethod,
			&i.Amount,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByOrderID = `-- name: GetTransactionByOrderID :one
SELECT 
    transaction_id,
    order_id,
    merchant_id,
    payment_method,
    amount,
    payment_status,
    created_at,
    updated_at
FROM transactions
WHERE order_id = $1
  AND deleted_at IS NULL
`

type GetTransactionByOrderIDRow struct {
	TransactionID int32            `json:"transaction_id"`
	OrderID       int32            `json:"order_id"`
	MerchantID    int32            `json:"merchant_id"`
	PaymentMethod string           `json:"payment_method"`
	Amount        int32            `json:"amount"`
	PaymentStatus string           `json:"payment_status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

// GetTransactionByOrderID: Retrieves transaction by order reference
// Purpose: Lookup transaction associated with specific order
// Parameters:
//
//	$1: order_id - The order ID to search by
//
// Returns: Transaction record if found and active
// Business Logic:
//   - Only returns non-deleted transactions
//   - Used for order payment verification
//   - Helps prevent duplicate payments
func (q *Queries) GetTransactionByOrderID(ctx context.Context, orderID int32) (*GetTransactionByOrderIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByOrderID, orderID)
	var i GetTransactionByOrderIDRow
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MerchantID,
		&i.PaymentMethod,
		&i.Amount,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT
    transaction_id, order_id, merchant_id, payment_method, amount, payment_status, created_at, updated_at, deleted_at,
    COUNT(*) OVER() AS total_count
FROM transactions
WHERE deleted_at IS NULL
  AND ($1::TEXT IS NULL OR payment_method ILIKE '%' || $1 || '%' OR payment_status ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetTransactionsRow struct {
	TransactionID int32            `json:"transaction_id"`
	OrderID       int32            `json:"order_id"`
	MerchantID    int32            `json:"merchant_id"`
	PaymentMethod string           `json:"payment_method"`
	Amount        int32            `json:"amount"`
	PaymentStatus string           `json:"payment_status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	TotalCount    int64            `json:"total_count"`
}

func (q *Queries) GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]*GetTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getTransactions, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetTransactionsRow
	for rows.Next() {
		var i GetTransactionsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.OrderID,
			&i.MerchantID,
			&i.PaymentMethod,
			&i.Amount,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsActive = `-- name: GetTransactionsActive :many
SELECT
    transaction_id, order_id, merchant_id, payment_method, amount, payment_status, created_at, updated_at, deleted_at,
    COUNT(*) OVER() AS total_count
FROM transactions
WHERE deleted_at IS NULL
AND ($1::TEXT IS NULL OR payment_method ILIKE '%' || $1 || '%' OR payment_status ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionsActiveParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetTransactionsActiveRow struct {
	TransactionID int32            `json:"transaction_id"`
	OrderID       int32            `json:"order_id"`
	MerchantID    int32            `json:"merchant_id"`
	PaymentMethod string           `json:"payment_method"`
	Amount        int32            `json:"amount"`
	PaymentStatus string           `json:"payment_status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	TotalCount    int64            `json:"total_count"`
}

// GetTransactionsActive: Retrieves paginated list of active transactions (identical to GetTransactions)
// Purpose: Maintains consistent API pattern with other active/trashed endpoints
// Parameters:
//
//	$1: search_term - Optional filter text for payment method/status
//	$2: limit - Pagination limit
//	$3: offset - Pagination offset
//
// Returns:
//
//	Active transaction records with total_count
//
// Business Logic:
//   - Same functionality as GetTransactions
//   - Exists for consistency in API design patterns
//
// Note: Could be consolidated with GetTransactions if duplicate functionality is undesired
func (q *Queries) GetTransactionsActive(ctx context.Context, arg GetTransactionsActiveParams) ([]*GetTransactionsActiveRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsActive, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetTransactionsActiveRow
	for rows.Next() {
		var i GetTransactionsActiveRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.OrderID,
			&i.MerchantID,
			&i.PaymentMethod,
			&i.Amount,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsTrashed = `-- name: GetTransactionsTrashed :many
SELECT
    transaction_id, order_id, merchant_id, payment_method, amount, payment_status, created_at, updated_at, deleted_at,
    COUNT(*) OVER() AS total_count
FROM transactions
WHERE deleted_at IS NOT NULL
AND ($1::TEXT IS NULL OR payment_method ILIKE '%' || $1 || '%' OR payment_status ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionsTrashedParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetTransactionsTrashedRow struct {
	TransactionID int32            `json:"transaction_id"`
	OrderID       int32            `json:"order_id"`
	MerchantID    int32            `json:"merchant_id"`
	PaymentMethod string           `json:"payment_method"`
	Amount        int32            `json:"amount"`
	PaymentStatus string           `json:"payment_status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	TotalCount    int64            `json:"total_count"`
}

// GetTransactionsTrashed: Retrieves paginated list of soft-deleted transactions
// Purpose: View and manage deleted transactions for audit/recovery
// Parameters:
//
//	$1: search_term - Optional text to filter trashed transactions
//	$2: limit - Maximum records per page
//	$3: offset - Records to skip
//
// Returns:
//
//	Trashed transaction records with total_count
//
// Business Logic:
//   - Only returns soft-deleted records (deleted_at IS NOT NULL)
//   - Maintains same search functionality as active transaction queries
//   - Preserves chronological sorting (newest first)
//   - Used in transaction recovery/audit interfaces
//   - Includes total_count for pagination in trash management UI
func (q *Queries) GetTransactionsTrashed(ctx context.Context, arg GetTransactionsTrashedParams) ([]*GetTransactionsTrashedRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsTrashed, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetTransactionsTrashedRow
	for rows.Next() {
		var i GetTransactionsTrashedRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.OrderID,
			&i.MerchantID,
			&i.PaymentMethod,
			&i.Amount,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAllTransactions = `-- name: RestoreAllTransactions :exec
UPDATE transactions
SET
    deleted_at = NULL
WHERE
    deleted_at IS NOT NULL
`

// RestoreAllTransactions: Mass restoration of cancelled transactions
// Purpose: Recover all trashed transactions at once
// Business Logic:
//   - Reactivates all soft-deleted transactions
//   - No parameters needed (bulk operation)
//   - Typically used during system recovery
func (q *Queries) RestoreAllTransactions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreAllTransactions)
	return err
}

const restoreTransaction = `-- name: RestoreTransaction :one
UPDATE transactions
SET
    deleted_at = NULL
WHERE
    transaction_id = $1
    AND deleted_at IS NOT NULL
  RETURNING transaction_id,
    order_id,
    merchant_id,
    payment_method,
    amount,
    payment_status,
    created_at,
    updated_at,
    deleted_at
`

// RestoreTransaction: Recovers a soft-deleted transaction
// Purpose: Reactivate a cancelled transaction
// Parameters:
//
//	$1: transaction_id - ID of transaction to restore
//
// Returns: The restored transaction record
// Business Logic:
//   - Nullifies deleted_at field
//   - Only works on previously cancelled transactions
//   - Maintains all original transaction data
func (q *Queries) RestoreTransaction(ctx context.Context, transactionID int32) (*Transaction, error) {
	row := q.db.QueryRow(ctx, restoreTransaction, transactionID)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MerchantID,
		&i.PaymentMethod,
		&i.Amount,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const trashTransaction = `-- name: TrashTransaction :one
UPDATE transactions
SET
    deleted_at = current_timestamp
WHERE
    transaction_id = $1
    AND deleted_at IS NULL
    RETURNING transaction_id,
    order_id,
    merchant_id,
    payment_method,
    amount,
    payment_status,
    created_at,
    updated_at,
    deleted_at
`

// TrashTransaction: Soft-deletes a transaction
// Purpose: Void/cancel a transaction without permanent deletion
// Parameters:
//
//	$1: transaction_id - ID of transaction to cancel
//
// Returns: The soft-deleted transaction record
// Business Logic:
//   - Sets deleted_at to current timestamp
//   - Preserves transaction for reporting
//   - Only processes active transactions
//   - Can be restored if needed
func (q *Queries) TrashTransaction(ctx context.Context, transactionID int32) (*Transaction, error) {
	row := q.db.QueryRow(ctx, trashTransaction, transactionID)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MerchantID,
		&i.PaymentMethod,
		&i.Amount,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET merchant_id = $2,
    payment_method = $3,
    amount = $4,
    payment_status = $5,
    order_id = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE transaction_id = $1
  AND deleted_at IS NULL
RETURNING transaction_id,
    order_id,
    merchant_id,
    payment_method,
    amount,
    payment_status,
    created_at,
    updated_at
`

type UpdateTransactionParams struct {
	TransactionID int32  `json:"transaction_id"`
	MerchantID    int32  `json:"merchant_id"`
	PaymentMethod string `json:"payment_method"`
	Amount        int32  `json:"amount"`
	PaymentStatus string `json:"payment_status"`
	OrderID       int32  `json:"order_id"`
}

type UpdateTransactionRow struct {
	TransactionID int32            `json:"transaction_id"`
	OrderID       int32            `json:"order_id"`
	MerchantID    int32            `json:"merchant_id"`
	PaymentMethod string           `json:"payment_method"`
	Amount        int32            `json:"amount"`
	PaymentStatus string           `json:"payment_status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

// UpdateTransaction: Modifies transaction details
// Purpose: Update transaction information
// Parameters:
//
//	$1: transaction_id - ID of transaction to update
//	$2: merchant_id - Updated merchant reference
//	$3: payment_method - Updated payment method
//	$4: amount - Updated transaction amount
//	$5: change_amount - Updated change amount
//	$6: payment_status - Updated payment status
//	$7: order_id - Updated order reference
//
// Returns: Updated transaction record
// Business Logic:
//   - Auto-updates updated_at timestamp
//   - Only modifies active transactions
//   - Validates all payment fields
//   - Used for payment corrections/updates
func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (*UpdateTransactionRow, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.TransactionID,
		arg.MerchantID,
		arg.PaymentMethod,
		arg.Amount,
		arg.PaymentStatus,
		arg.OrderID,
	)
	var i UpdateTransactionRow
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MerchantID,
		&i.PaymentMethod,
		&i.Amount,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
