// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: user_role/user_role_command.proto

package pb_user_role

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserRoleCommandService_AssignRoleToUser_FullMethodName   = "/pb.user_role.UserRoleCommandService/AssignRoleToUser"
	UserRoleCommandService_RemoveRoleFromUser_FullMethodName = "/pb.user_role.UserRoleCommandService/RemoveRoleFromUser"
)

// UserRoleCommandServiceClient is the client API for UserRoleCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRoleCommandServiceClient interface {
	AssignRoleToUser(ctx context.Context, in *AssignRoleToUserRequest, opts ...grpc.CallOption) (*ApiResponseUserRole, error)
	RemoveRoleFromUser(ctx context.Context, in *RemoveRoleFromUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type userRoleCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRoleCommandServiceClient(cc grpc.ClientConnInterface) UserRoleCommandServiceClient {
	return &userRoleCommandServiceClient{cc}
}

func (c *userRoleCommandServiceClient) AssignRoleToUser(ctx context.Context, in *AssignRoleToUserRequest, opts ...grpc.CallOption) (*ApiResponseUserRole, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseUserRole)
	err := c.cc.Invoke(ctx, UserRoleCommandService_AssignRoleToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleCommandServiceClient) RemoveRoleFromUser(ctx context.Context, in *RemoveRoleFromUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserRoleCommandService_RemoveRoleFromUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRoleCommandServiceServer is the server API for UserRoleCommandService service.
// All implementations must embed UnimplementedUserRoleCommandServiceServer
// for forward compatibility.
type UserRoleCommandServiceServer interface {
	AssignRoleToUser(context.Context, *AssignRoleToUserRequest) (*ApiResponseUserRole, error)
	RemoveRoleFromUser(context.Context, *RemoveRoleFromUserRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedUserRoleCommandServiceServer()
}

// UnimplementedUserRoleCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserRoleCommandServiceServer struct{}

func (UnimplementedUserRoleCommandServiceServer) AssignRoleToUser(context.Context, *AssignRoleToUserRequest) (*ApiResponseUserRole, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignRoleToUser not implemented")
}
func (UnimplementedUserRoleCommandServiceServer) RemoveRoleFromUser(context.Context, *RemoveRoleFromUserRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRoleFromUser not implemented")
}
func (UnimplementedUserRoleCommandServiceServer) mustEmbedUnimplementedUserRoleCommandServiceServer() {
}
func (UnimplementedUserRoleCommandServiceServer) testEmbeddedByValue() {}

// UnsafeUserRoleCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRoleCommandServiceServer will
// result in compilation errors.
type UnsafeUserRoleCommandServiceServer interface {
	mustEmbedUnimplementedUserRoleCommandServiceServer()
}

func RegisterUserRoleCommandServiceServer(s grpc.ServiceRegistrar, srv UserRoleCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedUserRoleCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserRoleCommandService_ServiceDesc, srv)
}

func _UserRoleCommandService_AssignRoleToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRoleToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleCommandServiceServer).AssignRoleToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleCommandService_AssignRoleToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleCommandServiceServer).AssignRoleToUser(ctx, req.(*AssignRoleToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleCommandService_RemoveRoleFromUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRoleFromUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleCommandServiceServer).RemoveRoleFromUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleCommandService_RemoveRoleFromUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleCommandServiceServer).RemoveRoleFromUser(ctx, req.(*RemoveRoleFromUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRoleCommandService_ServiceDesc is the grpc.ServiceDesc for UserRoleCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRoleCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.user_role.UserRoleCommandService",
	HandlerType: (*UserRoleCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignRoleToUser",
			Handler:    _UserRoleCommandService_AssignRoleToUser_Handler,
		},
		{
			MethodName: "RemoveRoleFromUser",
			Handler:    _UserRoleCommandService_RemoveRoleFromUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_role/user_role_command.proto",
}
