// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: user_role/user_role_query.proto

package pb_user_role

import (
	context "context"
	role "github.com/MamangRust/microservice-ecommerce-grpc-pb/role"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserRoleQueryService_FindByUserId_FullMethodName = "/pb.user_role.UserRoleQueryService/FindByUserId"
)

// UserRoleQueryServiceClient is the client API for UserRoleQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRoleQueryServiceClient interface {
	FindByUserId(ctx context.Context, in *FindByIdUserRoleRequest, opts ...grpc.CallOption) (*role.ApiResponsesRole, error)
}

type userRoleQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRoleQueryServiceClient(cc grpc.ClientConnInterface) UserRoleQueryServiceClient {
	return &userRoleQueryServiceClient{cc}
}

func (c *userRoleQueryServiceClient) FindByUserId(ctx context.Context, in *FindByIdUserRoleRequest, opts ...grpc.CallOption) (*role.ApiResponsesRole, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(role.ApiResponsesRole)
	err := c.cc.Invoke(ctx, UserRoleQueryService_FindByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRoleQueryServiceServer is the server API for UserRoleQueryService service.
// All implementations must embed UnimplementedUserRoleQueryServiceServer
// for forward compatibility.
type UserRoleQueryServiceServer interface {
	FindByUserId(context.Context, *FindByIdUserRoleRequest) (*role.ApiResponsesRole, error)
	mustEmbedUnimplementedUserRoleQueryServiceServer()
}

// UnimplementedUserRoleQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserRoleQueryServiceServer struct{}

func (UnimplementedUserRoleQueryServiceServer) FindByUserId(context.Context, *FindByIdUserRoleRequest) (*role.ApiResponsesRole, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByUserId not implemented")
}
func (UnimplementedUserRoleQueryServiceServer) mustEmbedUnimplementedUserRoleQueryServiceServer() {}
func (UnimplementedUserRoleQueryServiceServer) testEmbeddedByValue()                              {}

// UnsafeUserRoleQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRoleQueryServiceServer will
// result in compilation errors.
type UnsafeUserRoleQueryServiceServer interface {
	mustEmbedUnimplementedUserRoleQueryServiceServer()
}

func RegisterUserRoleQueryServiceServer(s grpc.ServiceRegistrar, srv UserRoleQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedUserRoleQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserRoleQueryService_ServiceDesc, srv)
}

func _UserRoleQueryService_FindByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleQueryServiceServer).FindByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleQueryService_FindByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleQueryServiceServer).FindByUserId(ctx, req.(*FindByIdUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRoleQueryService_ServiceDesc is the grpc.ServiceDesc for UserRoleQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRoleQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.user_role.UserRoleQueryService",
	HandlerType: (*UserRoleQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindByUserId",
			Handler:    _UserRoleQueryService_FindByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_role/user_role_query.proto",
}
