// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: user_role/user_role_command.proto

package pb_user_role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_role_user_role_command_proto protoreflect.FileDescriptor

const file_user_role_user_role_command_proto_rawDesc = "" +
	"\n" +
	"!user_role/user_role_command.proto\x12\fpb.user_role\x1a\x1bgoogle/protobuf/empty.proto\x1a user_role/user_role_common.proto2\xcd\x01\n" +
	"\x16UserRoleCommandService\x12\\\n" +
	"\x10AssignRoleToUser\x12%.pb.user_role.AssignRoleToUserRequest\x1a!.pb.user_role.ApiResponseUserRole\x12U\n" +
	"\x12RemoveRoleFromUser\x12'.pb.user_role.RemoveRoleFromUserRequest\x1a\x16.google.protobuf.EmptyBMZKgithub.com/MamangRust/microservice-ecommerce-grpc-pb/user_role;pb_user_roleb\x06proto3"

var file_user_role_user_role_command_proto_goTypes = []any{
	(*AssignRoleToUserRequest)(nil),   // 0: pb.user_role.AssignRoleToUserRequest
	(*RemoveRoleFromUserRequest)(nil), // 1: pb.user_role.RemoveRoleFromUserRequest
	(*ApiResponseUserRole)(nil),       // 2: pb.user_role.ApiResponseUserRole
	(*emptypb.Empty)(nil),             // 3: google.protobuf.Empty
}
var file_user_role_user_role_command_proto_depIdxs = []int32{
	0, // 0: pb.user_role.UserRoleCommandService.AssignRoleToUser:input_type -> pb.user_role.AssignRoleToUserRequest
	1, // 1: pb.user_role.UserRoleCommandService.RemoveRoleFromUser:input_type -> pb.user_role.RemoveRoleFromUserRequest
	2, // 2: pb.user_role.UserRoleCommandService.AssignRoleToUser:output_type -> pb.user_role.ApiResponseUserRole
	3, // 3: pb.user_role.UserRoleCommandService.RemoveRoleFromUser:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_role_user_role_command_proto_init() }
func file_user_role_user_role_command_proto_init() {
	if File_user_role_user_role_command_proto != nil {
		return
	}
	file_user_role_user_role_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_role_user_role_command_proto_rawDesc), len(file_user_role_user_role_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_role_user_role_command_proto_goTypes,
		DependencyIndexes: file_user_role_user_role_command_proto_depIdxs,
	}.Build()
	File_user_role_user_role_command_proto = out.File
	file_user_role_user_role_command_proto_goTypes = nil
	file_user_role_user_role_command_proto_depIdxs = nil
}
