// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	CartID    int32            `json:"cart_id"`
	UserID    int32            `json:"user_id"`
	ProductID int32            `json:"product_id"`
	Name      string           `json:"name"`
	Price     int32            `json:"price"`
	Image     string           `json:"image"`
	Quantity  int32            `json:"quantity"`
	Weight    int32            `json:"weight"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}
