// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MerchantDetail struct {
	MerchantDetailID int32            `json:"merchant_detail_id"`
	MerchantID       int32            `json:"merchant_id"`
	DisplayName      *string          `json:"display_name"`
	CoverImageUrl    *string          `json:"cover_image_url"`
	LogoUrl          *string          `json:"logo_url"`
	ShortDescription *string          `json:"short_description"`
	WebsiteUrl       *string          `json:"website_url"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
}

type MerchantSocialMediaLink struct {
	MerchantSocialID int32            `json:"merchant_social_id"`
	MerchantDetailID int32            `json:"merchant_detail_id"`
	Platform         string           `json:"platform"`
	Url              string           `json:"url"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
}
