// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// CreateMerchantDetail: Inserts a new merchant detail record
	// Purpose: Register profile details for a merchant
	// Parameters:
	//   $1: merchant_id
	//   $2: display_name
	//   $3: cover_image_url
	//   $4: logo_url
	//   $5: short_description
	//   $6: website_url
	// Returns: The newly created merchant detail record
	CreateMerchantDetail(ctx context.Context, arg CreateMerchantDetailParams) (*CreateMerchantDetailRow, error)
	// CreateMerchantSocialMediaLink: Inserts a new merchant social media link
	// Purpose: Register a new social media link for a merchant
	// Parameters:
	//   $1: merchant_detail_id
	//   $2: platform
	//   $3: url
	// Returns: The newly created social media link
	// Business Logic:
	//   - Sets created_at, updated_at automatically
	CreateMerchantSocialMediaLink(ctx context.Context, arg CreateMerchantSocialMediaLinkParams) (*CreateMerchantSocialMediaLinkRow, error)
	// DeleteAllMerchantSocialMediaLinksPermanently: Hard-deletes all soft-deleted social media links
	// Purpose: Permanently remove all trashed links
	// Business Logic:
	//   - Irreversible delete
	//   - Only affects already soft-deleted records
	DeleteAllMerchantSocialMediaLinksPermanently(ctx context.Context) error
	// DeleteAllPermanentMerchantDetails: Permanently delete all soft-deleted records
	DeleteAllPermanentMerchantDetails(ctx context.Context) error
	// DeleteMerchantDetailPermanently: Hard delete a merchant detail
	// Parameters:
	//   $1: merchant_detail_id
	DeleteMerchantDetailPermanently(ctx context.Context, merchantDetailID int32) error
	// DeleteMerchantSocialMediaLinkPermanently: Hard-deletes a social media link
	// Purpose: Permanently remove a link
	// Parameters:
	//   $1: merchant_social_id
	DeleteMerchantSocialMediaLinkPermanently(ctx context.Context, merchantSocialID int32) error
	// GetMerchantDetail: Retrieves a single merchant detail that is not soft-deleted
	// Parameters:
	//   $1: merchant_detail_id - ID of the merchant detail
	// Business Logic:
	//   - Returns the merchant detail where deleted_at IS NULL
	// Returns: A single merchant_details record with social media links
	// Note: merchants lives in the merchant service DB (per-service split), so the
	//   cross-DB JOIN is removed and merchant_name is a placeholder.
	GetMerchantDetail(ctx context.Context, merchantDetailID int32) (*GetMerchantDetailRow, error)
	// GetMerchantDetailTrashed: Fetches a single category by its ID
	// Purpose: Retrieve details of an active (non-deleted) category
	// Parameters:
	//   $1: Category ID to search for
	// Returns:
	//   Full category record if found and not deleted
	// Business Logic:
	//   - Excludes soft-deleted categories
	GetMerchantDetailTrashed(ctx context.Context, merchantDetailID int32) (*GetMerchantDetailTrashedRow, error)
	// GetMerchantDetails: Retrieves all merchant details regardless of merchant status
	// Parameters:
	//   $1: search - Keyword to filter merchant name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns: Merchant detail records matching the search, with total_count and social media links
	// Note: merchants lives in the merchant service DB (per-service split), so the
	//   cross-DB JOIN is removed and merchant_name is a placeholder; the search
	//   param is kept for signature stability and matches everything.
	GetMerchantDetails(ctx context.Context, arg GetMerchantDetailsParams) ([]*GetMerchantDetailsRow, error)
	// GetMerchantDetailsActive: Retrieves merchant details for active merchants
	// Parameters:
	//   $1: search - Keyword to filter merchant name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns: Active merchant detail records matching the search, with total_count and social media links
	// Note: merchants lives in the merchant service DB (per-service split), so the
	//   cross-DB JOIN is removed and merchant_name is a placeholder; the search
	//   param is kept for signature stability and matches everything.
	GetMerchantDetailsActive(ctx context.Context, arg GetMerchantDetailsActiveParams) ([]*GetMerchantDetailsActiveRow, error)
	// GetMerchantDetailsTrashed: Retrieves merchant details for soft-deleted merchants
	// Parameters:
	//   $1: search - Keyword to filter merchant name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns: Trashed merchant detail records matching the search, with total_count and social media links
	// Note: merchants lives in the merchant service DB (per-service split), so the
	//   cross-DB JOIN is removed and merchant_name is a placeholder; the search
	//   param is kept for signature stability and matches everything.
	GetMerchantDetailsTrashed(ctx context.Context, arg GetMerchantDetailsTrashedParams) ([]*GetMerchantDetailsTrashedRow, error)
	// RestoreAllMerchantDetails: Restores all soft-deleted merchant details
	RestoreAllMerchantDetails(ctx context.Context) error
	// RestoreAllMerchantSocialMediaLinks: Restores all soft-deleted social media links
	// Purpose: Bulk recovery operation
	// Business Logic:
	//   - Clears deleted_at on all trashed records
	RestoreAllMerchantSocialMediaLinks(ctx context.Context) error
	// RestoreMerchantDetail: Restores a soft-deleted merchant detail
	// Purpose: Reactivate previously hidden profile
	// Parameters:
	//   $1: merchant_detail_id
	// Returns: The restored record
	RestoreMerchantDetail(ctx context.Context, merchantDetailID int32) (*MerchantDetail, error)
	// RestoreMerchantSocialMediaLink: Restores a soft-deleted social media link
	// Purpose: Reactivate a previously deleted link
	// Parameters:
	//   $1: merchant_social_id
	// Returns: The restored social media link
	// Business Logic:
	//   - Clears deleted_at
	//   - Only works on previously soft-deleted entries
	RestoreMerchantSocialMediaLink(ctx context.Context, merchantSocialID int32) (*MerchantSocialMediaLink, error)
	// TrashMerchantDetail: Soft-deletes a merchant detail
	// Purpose: Temporarily hide the merchant profile
	// Parameters:
	//   $1: merchant_detail_id
	// Returns: The soft-deleted detail record
	TrashMerchantDetail(ctx context.Context, merchantDetailID int32) (*MerchantDetail, error)
	// TrashMerchantSocialMediaLink: Soft-deletes a merchant social media link
	// Purpose: Temporarily deactivate a link without permanent deletion
	// Parameters:
	//   $1: merchant_social_id
	// Returns: The soft-deleted social media link
	// Business Logic:
	//   - Sets deleted_at timestamp
	//   - Only affects active records
	TrashMerchantSocialMediaLink(ctx context.Context, merchantSocialID int32) (*MerchantSocialMediaLink, error)
	// UpdateMerchantDetail: Updates an existing merchant detail record
	// Purpose: Modify merchant profile
	// Parameters:
	//   $1: merchant_detail_id
	//   $2: display_name
	//   $3: cover_image_url
	//   $4: logo_url
	//   $5: short_description
	//   $6: website_url
	// Returns: The updated merchant detail
	UpdateMerchantDetail(ctx context.Context, arg UpdateMerchantDetailParams) (*UpdateMerchantDetailRow, error)
	// UpdateMerchantSocialMediaLink: Updates an existing merchant social media link
	// Purpose: Modify platform or URL
	// Parameters:
	//   $1: merchant_social_id
	//   $2: platform
	//   $3: url
	// Returns: The updated social media link
	// Business Logic:
	//   - Automatically updates updated_at timestamps
	//   - Only affects non-deleted records
	UpdateMerchantSocialMediaLink(ctx context.Context, arg UpdateMerchantSocialMediaLinkParams) (*UpdateMerchantSocialMediaLinkRow, error)
}

var _ Querier = (*Queries)(nil)
