// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO
    categories (
        name,
        description,
        slug_category,
        image_category
    )
VALUES ($1, $2, $3, $4)
RETURNING
    category_id,
    name,
    description,
    slug_category,
    image_category,
    created_at,
    updated_at
`

type CreateCategoryParams struct {
	Name          string  `json:"name"`
	Description   *string `json:"description"`
	SlugCategory  *string `json:"slug_category"`
	ImageCategory *string `json:"image_category"`
}

type CreateCategoryRow struct {
	CategoryID    int32            `json:"category_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	SlugCategory  *string          `json:"slug_category"`
	ImageCategory *string          `json:"image_category"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (*CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Description,
		arg.SlugCategory,
		arg.ImageCategory,
	)
	var i CreateCategoryRow
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.SlugCategory,
		&i.ImageCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteAllPermanentCategories = `-- name: DeleteAllPermanentCategories :exec
DELETE FROM categories WHERE deleted_at IS NOT NULL
`

// DeleteAllPermanentCategories: Permanently deletes all trashed categories
// Purpose: Bulk purge of all soft-deleted category records
// Parameters: None
// Returns: None
// Business Logic:
//   - Only affects records marked as deleted
func (q *Queries) DeleteAllPermanentCategories(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllPermanentCategories)
	return err
}

const deleteCategoryPermanently = `-- name: DeleteCategoryPermanently :exec
DELETE FROM categories
WHERE
    category_id = $1
    AND deleted_at IS NOT NULL
`

// DeleteCategoryPermanently: Removes a soft-deleted category permanently
// Purpose: Final cleanup of trashed categories
// Parameters:
//
//	$1: Category ID
//
// Returns:
//
//	Nothing (command only)
//
// Business Logic:
//   - Ensures category is deleted only if it has been soft-deleted
func (q *Queries) DeleteCategoryPermanently(ctx context.Context, categoryID int32) error {
	_, err := q.db.Exec(ctx, deleteCategoryPermanently, categoryID)
	return err
}

const getCategories = `-- name: GetCategories :many
SELECT
    category_id,
    name,
    description,
    slug_category,
    image_category,
    created_at,
    updated_at,
    COUNT(*) OVER () AS total_count
FROM categories
WHERE
    deleted_at IS NULL
    AND (
        $1::TEXT IS NULL
        OR name ILIKE '%' || $1 || '%'
        OR slug_category ILIKE '%' || $1 || '%'
    )
ORDER BY created_at DESC
LIMIT $2
OFFSET
    $3
`

type GetCategoriesParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetCategoriesRow struct {
	CategoryID    int32            `json:"category_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	SlugCategory  *string          `json:"slug_category"`
	ImageCategory *string          `json:"image_category"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	TotalCount    int64            `json:"total_count"`
}

func (q *Queries) GetCategories(ctx context.Context, arg GetCategoriesParams) ([]*GetCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getCategories, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetCategoriesRow
	for rows.Next() {
		var i GetCategoriesRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.SlugCategory,
			&i.ImageCategory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesActive = `-- name: GetCategoriesActive :many
SELECT
    category_id,
    name,
    description,
    slug_category,
    image_category,
    created_at,
    updated_at,
    deleted_at,
    COUNT(*) OVER () AS total_count
FROM categories
WHERE
    deleted_at IS NULL
    AND (
        $1::TEXT IS NULL
        OR name ILIKE '%' || $1 || '%'
        OR slug_category ILIKE '%' || $1 || '%'
    )
ORDER BY created_at DESC
LIMIT $2
OFFSET
    $3
`

type GetCategoriesActiveParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetCategoriesActiveRow struct {
	CategoryID    int32            `json:"category_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	SlugCategory  *string          `json:"slug_category"`
	ImageCategory *string          `json:"image_category"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	TotalCount    int64            `json:"total_count"`
}

// GetCategoriesActive: Retrieves paginated list of active categories with search capability
// Purpose: List all active product categories for management UI
// Parameters:
//
//	$1: search_term - Optional text to filter categories by name or slug (NULL for no filter)
//	$2: limit - Maximum number of records to return
//	$3: offset - Number of records to skip for pagination
//
// Returns:
//
//	All category fields plus total_count of matching records
//
// Business Logic:
//   - Excludes soft-deleted categories (deleted_at IS NULL)
//   - Supports partial text matching on name and slug_category fields (case-insensitive)
//   - Returns newest categories first (created_at DESC)
//   - Provides total_count for pagination calculations
func (q *Queries) GetCategoriesActive(ctx context.Context, arg GetCategoriesActiveParams) ([]*GetCategoriesActiveRow, error) {
	rows, err := q.db.Query(ctx, getCategoriesActive, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetCategoriesActiveRow
	for rows.Next() {
		var i GetCategoriesActiveRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.SlugCategory,
			&i.ImageCategory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesTrashed = `-- name: GetCategoriesTrashed :many
SELECT
    category_id,
    name,
    description,
    slug_category,
    image_category,
    created_at,
    updated_at,
    deleted_at,
    COUNT(*) OVER () AS total_count
FROM categories
WHERE
    deleted_at IS NOT NULL
    AND (
        $1::TEXT IS NULL
        OR name ILIKE '%' || $1 || '%'
        OR slug_category ILIKE '%' || $1 || '%'
    )
ORDER BY created_at DESC
LIMIT $2
OFFSET
    $3
`

type GetCategoriesTrashedParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type GetCategoriesTrashedRow struct {
	CategoryID    int32            `json:"category_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	SlugCategory  *string          `json:"slug_category"`
	ImageCategory *string          `json:"image_category"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	TotalCount    int64            `json:"total_count"`
}

// GetCategoriesTrashed: Retrieves paginated list of soft-deleted categories
// Purpose: View/manage deleted categories for potential restoration
// Parameters:
//
//	$1: search_term - Optional filter text (NULL for all trashed categories)
//	$2: limit - Pagination limit
//	$3: offset - Pagination offset
//
// Returns:
//
//	Trashed category records with total_count
//
// Business Logic:
//   - Only returns soft-deleted records (deleted_at IS NOT NULL)
//   - Same search functionality as active categories
//   - Maintains consistent sorting with active records
//   - Used in trash management/recovery interfaces
func (q *Queries) GetCategoriesTrashed(ctx context.Context, arg GetCategoriesTrashedParams) ([]*GetCategoriesTrashedRow, error) {
	rows, err := q.db.Query(ctx, getCategoriesTrashed, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetCategoriesTrashedRow
	for rows.Next() {
		var i GetCategoriesTrashedRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.SlugCategory,
			&i.ImageCategory,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT
    category_id,
    name,
    description,
    slug_category,
    image_category,
    created_at,
    updated_at
FROM categories
WHERE
    category_id = $1
    AND deleted_at IS NULL
`

type GetCategoryByIDRow struct {
	CategoryID    int32            `json:"category_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	SlugCategory  *string          `json:"slug_category"`
	ImageCategory *string          `json:"image_category"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

// GetCategoryByID: Fetches a single category by its ID
// Purpose: Retrieve details of an active (non-deleted) category
// Parameters:
//
//	$1: Category ID to search for
//
// Returns:
//
//	Full category record if found and not deleted
//
// Business Logic:
//   - Excludes soft-deleted categories
func (q *Queries) GetCategoryByID(ctx context.Context, categoryID int32) (*GetCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, categoryID)
	var i GetCategoryByIDRow
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.SlugCategory,
		&i.ImageCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCategoryByIDTrashed = `-- name: GetCategoryByIDTrashed :one
SELECT category_id, name, description, slug_category, image_category, created_at, updated_at, deleted_at
FROM categories
WHERE
    category_id = $1
    AND deleted_at IS NOT NULL
`

// GetCategoryByIDTrashed: Fetches a single category by its ID
// Purpose: Retrieve details of an active (non-deleted) category
// Parameters:
//
//	$1: Category ID to search for
//
// Returns:
//
//	Full category record if found and not deleted
//
// Business Logic:
//   - Excludes soft-deleted categories
func (q *Queries) GetCategoryByIDTrashed(ctx context.Context, categoryID int32) (*Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByIDTrashed, categoryID)
	var i Category
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.SlugCategory,
		&i.ImageCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const restoreAllCategories = `-- name: RestoreAllCategories :exec
UPDATE categories
SET
    deleted_at = NULL
WHERE
    deleted_at IS NOT NULL
`

// RestoreAllCategories: Recovers all trashed categories
// Purpose: Bulk restore of all soft-deleted category records
// Parameters: None
// Returns: None
// Business Logic:
//   - Resets deleted_at for all soft-deleted records
func (q *Queries) RestoreAllCategories(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreAllCategories)
	return err
}

const restoreCategory = `-- name: RestoreCategory :one
UPDATE categories
SET
    deleted_at = NULL
WHERE
    category_id = $1
    AND deleted_at IS NOT NULL
RETURNING
    category_id,
    name,
    description,
    slug_category,
    image_category,
    created_at,
    updated_at, deleted_at
`

// RestoreCategory: Recovers a previously trashed category
// Purpose: Restores a soft-deleted category for reuse
// Parameters:
//
//	$1: Category ID
//
// Returns:
//
//	Restored category record
//
// Business Logic:
//   - Only applies to categories currently marked as deleted
func (q *Queries) RestoreCategory(ctx context.Context, categoryID int32) (*Category, error) {
	row := q.db.QueryRow(ctx, restoreCategory, categoryID)
	var i Category
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.SlugCategory,
		&i.ImageCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const trashCategory = `-- name: TrashCategory :one
UPDATE categories
SET
    deleted_at = current_timestamp
WHERE
    category_id = $1
    AND deleted_at IS NULL
RETURNING
    category_id,
    name,
    description,
    slug_category,
    image_category,
    created_at,
    updated_at,
    deleted_at
`

// TrashCategory: Soft-deletes a category
// Purpose: Moves category to trash without permanent deletion
// Parameters:
//
//	$1: Category ID
//
// Returns:
//
//	The soft-deleted category record
//
// Business Logic:
//   - Updates deleted_at with current timestamp
//   - Prevents repeat trashing of already-deleted records
func (q *Queries) TrashCategory(ctx context.Context, categoryID int32) (*Category, error) {
	row := q.db.QueryRow(ctx, trashCategory, categoryID)
	var i Category
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.SlugCategory,
		&i.ImageCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = $2,
    description = $3,
    slug_category = $4,
    image_category = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE
    category_id = $1
    AND deleted_at IS NULL
RETURNING
    category_id,
    name,
    description,
    slug_category,
    image_category,
    created_at,
    updated_at
`

type UpdateCategoryParams struct {
	CategoryID    int32   `json:"category_id"`
	Name          string  `json:"name"`
	Description   *string `json:"description"`
	SlugCategory  *string `json:"slug_category"`
	ImageCategory *string `json:"image_category"`
}

type UpdateCategoryRow struct {
	CategoryID    int32            `json:"category_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	SlugCategory  *string          `json:"slug_category"`
	ImageCategory *string          `json:"image_category"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

// UpdateCategory: Updates category details
// Purpose: Modify existing category data while maintaining soft delete integrity
// Parameters:
//
//	$1: Category ID
//	$2: Updated name
//	$3: Updated description
//	$4: Updated slug
//
// Returns:
//
//	Updated category record
//
// Business Logic:
//   - Automatically updates the updated_at field
//   - Skips if category has been soft-deleted
func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (*UpdateCategoryRow, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.SlugCategory,
		arg.ImageCategory,
	)
	var i UpdateCategoryRow
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.SlugCategory,
		&i.ImageCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
