// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	CategoryID    int32            `json:"category_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	SlugCategory  *string          `json:"slug_category"`
	ImageCategory *string          `json:"image_category"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
}
