// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (*CreateCategoryRow, error)
	// DeleteAllPermanentCategories: Permanently deletes all trashed categories
	// Purpose: Bulk purge of all soft-deleted category records
	// Parameters: None
	// Returns: None
	// Business Logic:
	//   - Only affects records marked as deleted
	DeleteAllPermanentCategories(ctx context.Context) error
	// DeleteCategoryPermanently: Removes a soft-deleted category permanently
	// Purpose: Final cleanup of trashed categories
	// Parameters:
	//   $1: Category ID
	// Returns:
	//   Nothing (command only)
	// Business Logic:
	//   - Ensures category is deleted only if it has been soft-deleted
	DeleteCategoryPermanently(ctx context.Context, categoryID int32) error
	GetCategories(ctx context.Context, arg GetCategoriesParams) ([]*GetCategoriesRow, error)
	// GetCategoriesActive: Retrieves paginated list of active categories with search capability
	// Purpose: List all active product categories for management UI
	// Parameters:
	//   $1: search_term - Optional text to filter categories by name or slug (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All category fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted categories (deleted_at IS NULL)
	//   - Supports partial text matching on name and slug_category fields (case-insensitive)
	//   - Returns newest categories first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetCategoriesActive(ctx context.Context, arg GetCategoriesActiveParams) ([]*GetCategoriesActiveRow, error)
	// GetCategoriesTrashed: Retrieves paginated list of soft-deleted categories
	// Purpose: View/manage deleted categories for potential restoration
	// Parameters:
	//   $1: search_term - Optional filter text (NULL for all trashed categories)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Returns:
	//   Trashed category records with total_count
	// Business Logic:
	//   - Only returns soft-deleted records (deleted_at IS NOT NULL)
	//   - Same search functionality as active categories
	//   - Maintains consistent sorting with active records
	//   - Used in trash management/recovery interfaces
	GetCategoriesTrashed(ctx context.Context, arg GetCategoriesTrashedParams) ([]*GetCategoriesTrashedRow, error)
	// GetCategoryByID: Fetches a single category by its ID
	// Purpose: Retrieve details of an active (non-deleted) category
	// Parameters:
	//   $1: Category ID to search for
	// Returns:
	//   Full category record if found and not deleted
	// Business Logic:
	//   - Excludes soft-deleted categories
	GetCategoryByID(ctx context.Context, categoryID int32) (*GetCategoryByIDRow, error)
	// GetCategoryByIDTrashed: Fetches a single category by its ID
	// Purpose: Retrieve details of an active (non-deleted) category
	// Parameters:
	//   $1: Category ID to search for
	// Returns:
	//   Full category record if found and not deleted
	// Business Logic:
	//   - Excludes soft-deleted categories
	GetCategoryByIDTrashed(ctx context.Context, categoryID int32) (*Category, error)
	// RestoreAllCategories: Recovers all trashed categories
	// Purpose: Bulk restore of all soft-deleted category records
	// Parameters: None
	// Returns: None
	// Business Logic:
	//   - Resets deleted_at for all soft-deleted records
	RestoreAllCategories(ctx context.Context) error
	// RestoreCategory: Recovers a previously trashed category
	// Purpose: Restores a soft-deleted category for reuse
	// Parameters:
	//   $1: Category ID
	// Returns:
	//   Restored category record
	// Business Logic:
	//   - Only applies to categories currently marked as deleted
	RestoreCategory(ctx context.Context, categoryID int32) (*Category, error)
	// TrashCategory: Soft-deletes a category
	// Purpose: Moves category to trash without permanent deletion
	// Parameters:
	//   $1: Category ID
	// Returns:
	//   The soft-deleted category record
	// Business Logic:
	//   - Updates deleted_at with current timestamp
	//   - Prevents repeat trashing of already-deleted records
	TrashCategory(ctx context.Context, categoryID int32) (*Category, error)
	// UpdateCategory: Updates category details
	// Purpose: Modify existing category data while maintaining soft delete integrity
	// Parameters:
	//   $1: Category ID
	//   $2: Updated name
	//   $3: Updated description
	//   $4: Updated slug
	// Returns:
	//   Updated category record
	// Business Logic:
	//   - Automatically updates the updated_at field
	//   - Skips if category has been soft-deleted
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (*UpdateCategoryRow, error)
}

var _ Querier = (*Queries)(nil)
