// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// CreateSlider: Creates a new slider entry
	// Membuat slider baru
	// Parameters:
	//   $1: name - Nama/judul slider
	//   $2: image - URL gambar slider
	// Returns:
	//   The complete created slider record
	//   Seluruh record slider yang baru dibuat
	// Business Logic:
	//   - Creates a new active slider
	//   - Membuat slider aktif baru
	//   - Requires both name and image
	//   - Memerlukan nama dan gambar
	CreateSlider(ctx context.Context, arg CreateSliderParams) (*CreateSliderRow, error)
	// DeleteAllPermanentSliders: Permanently removes all trashed sliders
	// Menghapus permanen semua slider yang di-trash
	// Parameters: None
	// Returns:
	//   Nothing (exec-only)
	// Business Logic:
	//   - Admin-level bulk deletion
	//   - Operasi penghapusan massal level admin
	//   - Irreversible operation
	//   - Operasi tidak dapat dibatalkan
	DeleteAllPermanentSliders(ctx context.Context) error
	// DeleteSliderPermanently: Permanently removes a trashed slider
	// Menghapus permanen slider yang sudah di-trash
	// Parameters:
	//   $1: slider_id - ID slider yang akan dihapus permanen
	// Returns:
	//   Nothing (exec-only)
	//   Tidak mengembalikan apa pun (exec-only)
	// Business Logic:
	//   - Physical deletion from database
	//   - Penghapusan fisik dari database
	//   - Only works on already trashed sliders
	//   - Hanya bekerja pada slider yang sudah di-trash
	//   - Irreversible operation
	//   - Operasi tidak dapat dibatalkan
	DeleteSliderPermanently(ctx context.Context, sliderID int32) error
	// GetSliderByID: Retrieves a single active slider by ID
	// Mengambil satu slider aktif berdasarkan ID
	// Parameters:
	//   $1: slider_id - ID slider yang akan diambil
	// Returns:
	//   Complete slider record if found and active
	//   Seluruh record slider jika ditemukan dan aktif
	// Business Logic:
	//   - Only returns non-deleted (active) sliders
	//   - Hanya mengembalikan slider yang tidak terhapus (aktif)
	GetSliderByID(ctx context.Context, sliderID int32) (*GetSliderByIDRow, error)
	// GetSliders: Retrieves all sliders (active & trashed) with optional name search and pagination
	// Purpose: General listing of sliders regardless of status
	// Parameters:
	//   $1: search_term - Optional text to filter sliders by name (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All slider fields plus total_count of matching records
	// Business Logic:
	//   - Includes both active and trashed sliders
	//   - Supports partial text matching on name field (case-insensitive)
	//   - Returns newest sliders first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetSliders(ctx context.Context, arg GetSlidersParams) ([]*GetSlidersRow, error)
	// GetSlidersActive: Retrieves active sliders with optional name search and pagination
	// Purpose: Display active sliders for frontend/backend UI
	// Parameters:
	//   $1: search_term - Optional text to filter sliders by name (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All slider fields plus total_count of matching records
	// Business Logic:
	//   - Excludes soft-deleted sliders (deleted_at IS NULL)
	//   - Supports partial text matching on name field (case-insensitive)
	//   - Returns newest sliders first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetSlidersActive(ctx context.Context, arg GetSlidersActiveParams) ([]*GetSlidersActiveRow, error)
	// GetSlidersTrashed: Retrieves trashed sliders with optional name search and pagination
	// Purpose: Display deleted sliders in admin recycle bin
	// Parameters:
	//   $1: search_term - Optional text to filter sliders by name (NULL for no filter)
	//   $2: limit - Maximum number of records to return
	//   $3: offset - Number of records to skip for pagination
	// Returns:
	//   All slider fields plus total_count of matching records
	// Business Logic:
	//   - Only includes soft-deleted sliders (deleted_at IS NOT NULL)
	//   - Supports partial text matching on name field (case-insensitive)
	//   - Returns newest sliders first (created_at DESC)
	//   - Provides total_count for pagination calculations
	GetSlidersTrashed(ctx context.Context, arg GetSlidersTrashedParams) ([]*GetSlidersTrashedRow, error)
	// RestoreAllSliders: Recovers all trashed sliders
	// Memulihkan semua slider yang dihapus sementara
	// Parameters: None
	// Returns:
	//   Nothing (exec-only)
	// Business Logic:
	//   - Admin-level bulk restore operation
	//   - Operasi pemulihan massal level admin
	RestoreAllSliders(ctx context.Context) error
	// RestoreSlider: Recovers a soft-deleted slider
	// Memulihkan slider yang dihapus sementara
	// Parameters:
	//   $1: slider_id - ID slider yang akan dipulihkan
	// Returns:
	//   The restored slider record
	//   Record slider yang telah dipulihkan
	// Business Logic:
	//   - Clears the deleted_at field
	//   - Membersihkan field deleted_at
	//   - Only works on trashed sliders
	//   - Hanya bekerja pada slider yang dihapus sementara
	RestoreSlider(ctx context.Context, sliderID int32) (*Slider, error)
	// TrashSlider: Soft-deletes a slider
	// Menghapus sementara slider (soft delete)
	// Parameters:
	//   $1: slider_id - ID slider yang akan dihapus
	// Returns:
	//   The trashed slider record
	//   Record slider yang telah dihapus sementara
	// Business Logic:
	//   - Sets deleted_at timestamp
	//   - Menandai deleted_at timestamp
	//   - Only works on active sliders
	//   - Hanya bekerja pada slider aktif
	TrashSlider(ctx context.Context, sliderID int32) (*Slider, error)
	// UpdateSlider: Modifies an existing slider
	// Memperbarui slider yang sudah ada
	// Parameters:
	//   $1: slider_id - ID slider yang akan diperbarui
	//   $2: name - Nama baru slider
	//   $3: image - URL gambar baru slider
	// Returns:
	//   The updated slider record
	//   Record slider yang telah diperbarui
	// Business Logic:
	//   - Updates both name and image
	//   - Memperbarui nama dan gambar
	//   - Only works on active sliders
	//   - Hanya bekerja pada slider aktif
	//   - Automatically updates timestamp
	//   - Otomatis memperbarui timestamp
	UpdateSlider(ctx context.Context, arg UpdateSliderParams) (*UpdateSliderRow, error)
}

var _ Querier = (*Queries)(nil)
