// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderItem struct {
	OrderItemID int32            `json:"order_item_id"`
	OrderID     int32            `json:"order_id"`
	ProductID   int32            `json:"product_id"`
	Quantity    int32            `json:"quantity"`
	Price       int32            `json:"price"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}
