// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// CalculateTotalPrice: Calculates total price of active order items for a specific order
	// Purpose: Provides the aggregated monetary value of an order
	// Parameters:
	//   $1: order_id - identifier of the order
	// Returns:
	//   total_price: Sum of (quantity * price) for all active items in the order
	// Business Logic:
	//   - Ignores soft-deleted items
	//   - Ensures result is zero if no items exist
	CalculateTotalPrice(ctx context.Context, orderID int32) (int32, error)
	// CreateOrderItem: Inserts a new order item record
	// Purpose: Adds a product to a specific order
	// Parameters:
	//   $1: order_id
	//   $2: product_id
	//   $3: quantity
	//   $4: price
	// Returns:
	//   The newly created order item
	// Business Logic:
	//   - Assumes quantity and price are validated in application layer
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (*CreateOrderItemRow, error)
	// DeleteAllPermanentOrdersItem: Permanently deletes all trashed order items
	// Purpose: Performs hard delete of all soft-deleted items
	// Parameters: None
	// Returns: None
	// Business Logic:
	//   - Used for data cleanup or archival enforcement
	//   - The orders table lives in the order service database (per-service DB
	//     split), so items of trashed orders are cleaned by the order service via
	//     gRPC DeleteOrderItemByOrderPermanent instead of a cross-DB subquery.
	DeleteAllPermanentOrdersItem(ctx context.Context) error
	// DeleteOrderItemPermanently: Permanently deletes a trashed order item
	// Purpose: Removes the record entirely from the database
	// Parameters:
	//   $1: order_item_id
	// Returns: None
	// Business Logic:
	//   - Only deletes if already soft-deleted
	//   - Irreversible action
	DeleteOrderItemPermanently(ctx context.Context, orderItemID int32) error
	// DeleteOrderItemsByOrderPermanent: Permanently deletes all trashed order items for a specific order
	DeleteOrderItemsByOrderPermanent(ctx context.Context, orderID int32) error
	// GetOrderItems: Retrieves active order items with pagination and search
	// Purpose: Provides paginated listing of non-deleted order items for display or reporting
	// Parameters:
	//   $1: Search keyword (matches order_id or product_id, optional)
	//   $2: Limit (number of records per page)
	//   $3: Offset (starting record index)
	// Returns:
	//   All matching order item fields
	//   total_count: Total number of results ignoring pagination (for frontend pagination UI)
	// Business Logic:
	//   - Filters out soft-deleted items
	//   - Supports keyword-based filtering
	//   - Includes total result count via window function
	GetOrderItems(ctx context.Context, arg GetOrderItemsParams) ([]*GetOrderItemsRow, error)
	// GetOrderItemsActive: Retrieves active order items (duplicate-safe with GetOrderItems)
	// Purpose: Lists active (non-deleted) order items with pagination and optional search
	// Parameters:
	//   $1: Search keyword (order_id or product_id, optional)
	//   $2: Limit (pagination size)
	//   $3: Offset (pagination start)
	// Returns:
	//   Order item fields plus total matching count
	// Business Logic:
	//   - Behaves similarly to GetOrderItems
	//   - Used when clarity between active/trashed context is required
	GetOrderItemsActive(ctx context.Context, arg GetOrderItemsActiveParams) ([]*GetOrderItemsActiveRow, error)
	// GetOrderItemsByOrder: Retrieves active order items for a specific order
	// Purpose: Fetches all non-deleted order items under one order
	// Parameters:
	//   $1: order_id
	// Returns:
	//   List of active order items
	// Business Logic:
	//   - Excludes soft-deleted entries
	GetOrderItemsByOrder(ctx context.Context, orderID int32) ([]*GetOrderItemsByOrderRow, error)
	// GetOrderItemsTrashed: Retrieves soft-deleted order items with pagination
	// Purpose: Allows review and management of trashed order items
	// Parameters:
	//   $1: Search keyword (order_id or product_id, optional)
	//   $2: Limit (number of rows per page)
	//   $3: Offset (starting point for pagination)
	// Returns:
	//   All matching deleted order item fields
	//   total_count: Total number of trashed results
	// Business Logic:
	//   - Only includes records with non-null deleted_at (trashed)
	//   - Enables optional keyword search and pagination
	//   - Sorted by deletion date for recent trash activity review
	GetOrderItemsTrashed(ctx context.Context, arg GetOrderItemsTrashedParams) ([]*GetOrderItemsTrashedRow, error)
	// RestoreAllOrdersItem: Restores all soft-deleted order items
	// Purpose: Mass recovery of trashed items
	// Parameters: None
	// Returns: None
	// Business Logic:
	//   - Resets deleted_at to NULL for all trashed items
	RestoreAllOrdersItem(ctx context.Context) error
	// RestoreOrderItem: Restores a previously trashed order item
	// Purpose: Undoes a soft-delete action
	// Parameters:
	//   $1: order_item_id
	// Returns:
	//   The restored order item
	// Business Logic:
	//   - Only restores items currently soft-deleted
	RestoreOrderItem(ctx context.Context, orderItemID int32) (*OrderItem, error)
	// TrashOrderItem: Soft-deletes a specific order item
	// Purpose: Marks an item as deleted without removing it from DB
	// Parameters:
	//   $1: order_item_id
	// Returns:
	//   The soft-deleted order item
	// Business Logic:
	//   - Preserves record for potential restoration or audit
	TrashOrderItem(ctx context.Context, orderItemID int32) (*OrderItem, error)
	// UpdateOrderItem: Updates quantity and price of an existing order item
	// Purpose: Allows modification of product details in an order
	// Parameters:
	//   $1: order_item_id
	//   $2: new quantity
	//   $3: new price
	// Returns:
	//   The updated order item
	// Business Logic:
	//   - Applies changes only to active items
	//   - Automatically updates `updated_at` timestamp
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (*UpdateOrderItemRow, error)
}

var _ Querier = (*Queries)(nil)
