// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MerchantBusinessInformation struct {
	MerchantBusinessInfoID int32            `json:"merchant_business_info_id"`
	MerchantID             int32            `json:"merchant_id"`
	BusinessType           *string          `json:"business_type"`
	TaxID                  *string          `json:"tax_id"`
	EstablishedYear        *int32           `json:"established_year"`
	NumberOfEmployees      *int32           `json:"number_of_employees"`
	WebsiteUrl             *string          `json:"website_url"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	DeletedAt              pgtype.Timestamp `json:"deleted_at"`
}
