// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// CreateMerchantBusinessInformation: Inserts a new business info record
	// Purpose: Register extended business info for a merchant
	// Parameters:
	//   $1: merchant_id
	//   $2: business_type
	//   $3: tax_id
	//   $4: established_year
	//   $5: number_of_employees
	//   $6: website_url
	// Returns: The newly created business info record
	// Business Logic:
	//   - Sets created_at timestamp automatically
	//   - Validates all required fields
	CreateMerchantBusinessInformation(ctx context.Context, arg CreateMerchantBusinessInformationParams) (*CreateMerchantBusinessInformationRow, error)
	// DeleteAllPermanentMerchantBusinessInformation: Hard-deletes all trashed records
	// Purpose: Clean up all soft-deleted business info entries
	// Business Logic:
	//   - Irreversible bulk delete
	//   - Used during database cleanup/maintenance
	DeleteAllPermanentMerchantBusinessInformation(ctx context.Context) error
	// DeleteMerchantBusinessInformationPermanently: Hard-deletes a single record
	// Purpose: Completely remove soft-deleted business info
	// Parameters:
	//   $1: merchant_business_info_id
	// Business Logic:
	//   - Irreversible operation
	//   - Only affects already soft-deleted records
	DeleteMerchantBusinessInformationPermanently(ctx context.Context, merchantBusinessInfoID int32) error
	// GetMerchantBusinessInformation: Retrieves a single business information record that is not soft-deleted
	// Parameters:
	//   $1: merchant_business_info_id - ID of the business info
	// Business Logic:
	//   - Returns the merchant business information where deleted_at IS NULL
	// Returns: A single merchant_business_information record
	GetMerchantBusinessInformation(ctx context.Context, merchantBusinessInfoID int32) (*GetMerchantBusinessInformationRow, error)
	// GetMerchantsBusinessInformation: Retrieves all business info records with pagination and optional search
	// Parameters:
	//   $1: search - Keyword to filter merchant_name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Business Logic:
	//   - Fetches all merchant business information regardless of merchant status (active or deleted)
	//   - Supports case-insensitive partial search by merchant name
	//   - Applies pagination using limit and offset
	// Returns: All business info records matching the search, with total_count for pagination
	// Note: merchants lives in the merchant service DB (per-service split), so the
	//   cross-DB JOIN is removed and merchant_name is a placeholder; the search
	//   param is kept for signature stability and matches everything.
	GetMerchantsBusinessInformation(ctx context.Context, arg GetMerchantsBusinessInformationParams) ([]*GetMerchantsBusinessInformationRow, error)
	// GetMerchantsBusinessInformationActive: Retrieves business info for active (non-deleted) merchants with pagination and optional search
	// Parameters:
	//   $1: search - Keyword to filter merchant_name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Business Logic:
	//   - Fetches merchant business information for only active merchants (deleted_at IS NULL)
	//   - Supports case-insensitive partial search by merchant name
	//   - Applies pagination using limit and offset
	// Returns: Business info records for active merchants matching the search, with total_count
	// Note: merchants lives in the merchant service DB (per-service split), so the
	//   cross-DB JOIN is removed and merchant_name is a placeholder; the search
	//   param is kept for signature stability and matches everything.
	GetMerchantsBusinessInformationActive(ctx context.Context, arg GetMerchantsBusinessInformationActiveParams) ([]*GetMerchantsBusinessInformationActiveRow, error)
	// GetMerchantBusinessInformationTrashed: Retrieves business info for deleted merchants with pagination and optional search
	// Parameters:
	//   $1: search - Keyword to filter merchant_name (case-insensitive, partial match)
	//   $2: limit - Pagination limit
	//   $3: offset - Pagination offset
	// Business Logic:
	//   - Fetches merchant business information for only deleted merchants (deleted_at IS NOT NULL)
	//   - Supports case-insensitive partial search by merchant name
	//   - Applies pagination using limit and offset
	// Returns: Business info records for deleted merchants matching the search, with total_count
	// Note: merchants lives in the merchant service DB (per-service split), so the
	//   cross-DB JOIN is removed and merchant_name is a placeholder; the search
	//   param is kept for signature stability and matches everything.
	GetMerchantsBusinessInformationTrashed(ctx context.Context, arg GetMerchantsBusinessInformationTrashedParams) ([]*GetMerchantsBusinessInformationTrashedRow, error)
	// RestoreAllMerchantBusinessInformation: Restores all soft-deleted records
	// Purpose: Bulk recovery operation
	// Business Logic:
	//   - Clears deleted_at on all trashed records
	//   - Useful during data recovery or admin resets
	RestoreAllMerchantBusinessInformation(ctx context.Context) error
	// RestoreMerchantBusinessInformation: Restores a soft-deleted business info record
	// Purpose: Reactivate a previously trashed record
	// Parameters:
	//   $1: merchant_business_info_id
	// Returns: The restored business info record
	// Business Logic:
	//   - Clears deleted_at
	//   - Only works for soft-deleted entries
	RestoreMerchantBusinessInformation(ctx context.Context, merchantBusinessInfoID int32) (*MerchantBusinessInformation, error)
	// TrashMerchantBusinessInformation: Soft-deletes a business info record
	// Purpose: Deactivate business info without removing from DB
	// Parameters:
	//   $1: merchant_business_info_id
	// Returns: The soft-deleted record
	// Business Logic:
	//   - Sets deleted_at timestamp
	//   - Only affects active records
	TrashMerchantBusinessInformation(ctx context.Context, merchantBusinessInfoID int32) (*MerchantBusinessInformation, error)
	// UpdateMerchantBusinessInformation: Updates existing business info
	// Purpose: Modify business information details
	// Parameters:
	//   $1: merchant_business_info_id
	//   $2: business_type
	//   $3: tax_id
	//   $4: established_year
	//   $5: number_of_employees
	//   $6: website_url
	// Returns: The updated business info record
	// Business Logic:
	//   - Only affects active (non-deleted) records
	//   - Automatically updates the updated_at timestamp
	UpdateMerchantBusinessInformation(ctx context.Context, arg UpdateMerchantBusinessInformationParams) (*UpdateMerchantBusinessInformationRow, error)
}

var _ Querier = (*Queries)(nil)
