// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ProductID    int32            `json:"product_id"`
	MerchantID   int32            `json:"merchant_id"`
	CategoryID   int32            `json:"category_id"`
	Name         string           `json:"name"`
	Description  *string          `json:"description"`
	Price        int32            `json:"price"`
	CountInStock int32            `json:"count_in_stock"`
	Brand        *string          `json:"brand"`
	Weight       *int32           `json:"weight"`
	Rating       *float64         `json:"rating"`
	SlugProduct  *string          `json:"slug_product"`
	ImageProduct *string          `json:"image_product"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

type ProductStockAdjustment struct {
	OperationID string           `json:"operation_id"`
	ProductID   int32            `json:"product_id"`
	Delta       int32            `json:"delta"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
